### ISSUE TITLE
Error during update from version 8u252_b09-1 to 8u262_b10-1 on CentOS7

### ISSUE THREAD

**Issue by hnk** [AdoptOpenJDK/openjdk-support#145] opened 2020-07-20 10:15 UTC
## Question

Hello there, today my systems noted an update to adoptopenjdk-8-hotspot. Currently the systems run `adoptopenjdk-8-hotspot-8u252_b09-1.x86_64` and yum noted an available update to `adoptopenjdk-8-hotspot-8u262_b10-1.x86_64`.

The update fails with a transaction check error:
```
Transaction check error:
  file /usr/lib/jvm/adoptopenjdk-8-hotspot/man/ja from install of adoptopenjdk-8-hotspot-8u262_b10-1.x86_64 conflicts with file from package adoptopenjdk-8-hotspot-8u252_b09-1.x86_64
```

## Context

Java version:

```
[root@***** ~]# java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

Your operating system and platform:

We run CentOS 7 on x86-64 and have not had any issues updating in the past.

Provided here are the relevant logs as well as showing that both versions originate from the same repository:

```
[root@***** ~]# yum update adoptopenjdk-8-hotspot
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.23media.com
 * extras: ftp.hosteurope.de
 * updates: centos.intergenia.de
Abhängigkeiten werden aufgelöst
--> Transaktionsprüfung wird ausgeführt
---> Paket adoptopenjdk-8-hotspot.x86_64 0:8u252_b09-1 markiert, um aktualisiert zu werden
---> Paket adoptopenjdk-8-hotspot.x86_64 0:8u262_b10-1 markiert, um eine Aktualisierung zu werden
--> Abhängigkeitsauflösung beendet

Abhängigkeiten aufgelöst

=======================================================================================================================================================================================================================================
 Package                                                          Arch                                             Version                                                Paketquelle                                            Größe
=======================================================================================================================================================================================================================================
Aktualisieren:
 adoptopenjdk-8-hotspot                                           x86_64                                           8u262_b10-1                                            AdoptOpenJDK                                            98 M

Transaktionsübersicht
=======================================================================================================================================================================================================================================
Aktualisieren  1 Paket

Gesamtgröße: 98 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /usr/lib/jvm/adoptopenjdk-8-hotspot/man/ja from install of adoptopenjdk-8-hotspot-8u262_b10-1.x86_64 conflicts with file from package adoptopenjdk-8-hotspot-8u252_b09-1.x86_64

Fehler-Zusammenfassung
----------------------

[root@***** ~]# yum info adoptopenjdk-8-hotspot-8u252_b09-1.x86_64
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.23media.com
 * extras: ftp.hosteurope.de
 * updates: centos.intergenia.de
Installierte Pakete
Name       : adoptopenjdk-8-hotspot
Architektur : x86_64
Version    : 8u252_b09
Ausgabe    : 1
Größe : 194 M
Quelle      : installed
Aus Quelle  : AdoptOpenJDK
Zusammenfassung: OpenJDK Development Kit 8 (JDK) with Hotspot by AdoptOpenJDK
URL        : https://adoptopenjdk.net/
Lizenz      : GPL-2.0+CE
Beschreibung: OpenJDK Development Kit 8 (JDK) with Hotspot by AdoptOpenJDK

[root@***** ~]# yum info adoptopenjdk-8-hotspot-8u262_b10-1.x86_64
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.23media.com
 * extras: ftp.hosteurope.de
 * updates: centos.intergenia.de
Verfügbare Pakete
Name       : adoptopenjdk-8-hotspot
Architektur : x86_64
Version    : 8u262_b10
Ausgabe    : 1
Größe : 98 M
Quelle      : AdoptOpenJDK
Zusammenfassung: OpenJDK Development Kit 8 (JDK) with Hotspot by AdoptOpenJDK
URL        : https://adoptopenjdk.net/
Lizenz      : GPL-2.0+CE
Beschreibung: OpenJDK Development Kit 8 (JDK) with Hotspot by AdoptOpenJDK
```

I would appreciate any pointers to solving this issue. Currently I am stumpted. Since these also run on production systems, I do not want to remove the packages and do a re-install. But am open to this if it is needed.

**Comment by aahlenst** [comment] 2020-07-20 10:16
Duplicate of https://github.com/AdoptOpenJDK/openjdk-installer/issues/236. New packages are coming soon.

**Closed** 2020-07-20 12:35 UTC
Labels: duplicate

**Comment by aahlenst** [comment] 2020-07-20 12:43
The new packages for 8u262 are in. 11.0.8 is currently being uploaded. Might need `yum update --refresh` to get the `-2` package.
