### ISSUE TITLE
SIGSEGV (0xb) at pc=0x00007fe0a3beffaa, pid=1161, tid=1361

### ISSUE THREAD

**Issue by rhollencamp** [AdoptOpenJDK/openjdk-support#46] opened 2020-01-23 16:43 UTC
* **Platform and architecture (e.g. Linux/x64**:
CentOS Linux release 7.6.1810 (Core)

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
OpenJDK 64-Bit Server VM (11.0.5+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)

* **Variant e.g. HotSpot or OpenJ9**:
HotSpot

* **Have you tested it with other vendors' java**:
Has not been tested on a different vendor, but a different version of AdoptOpenJDK (8u192) works without issue

* **Steps to reproduce**:
Unknown; issue occurs at random

* **Error messsage and/or description of what is not working as expected**:
`SIGSEGV (0xb) at pc=0x00007fe0a3beffaa, pid=1161, tid=1361`
[hs_err_pid1161.log](https://github.com/AdoptOpenJDK/openjdk-support/files/4104286/hs_err_pid1161.log)

**Comment by gdams** [comment] 2020-01-23 17:51
Hi @rhollencamp thanks for the issue:

Can I ask you to check if this fails on an Azul Zulu 11 binary of the same version?

**Comment by rhollencamp** [comment] 2020-01-24 21:04
> Can I ask you to check if this fails on an Azul Zulu 11 binary of the same version?

We are only noticing this issue appear a handful of times a week across a decently sized prod cluster, and haven't been able to reproduce it in a non-production environment.

This means that the only way for me to answer that with any confidence is to switch all our prod machines to a different JVM 🙃 We are continuing to troubleshoot this in our end; if we do try a different JVM vendor it is likely to be centos-packaged OpenJDK

**Comment by karianna** [comment] 2020-01-26 06:58
> > Can I ask you to check if this fails on an Azul Zulu 11 binary of the same version?
> 
> We are only noticing this issue appear a handful of times a week across a decently sized prod cluster, and haven't been able to reproduce it in a non-production environment.
> 
> This means that the only way for me to answer that with any confidence is to switch all our prod machines to a different JVM 🙃 We are continuing to troubleshoot this in our end; if we do try a different JVM vendor it is likely to be centos-packaged OpenJDK

11.0.6 has been released - are you able to upgrade your PRD cluster to that?

**Comment by rhollencamp** [comment] 2020-01-27 13:38
> 11.0.6 has been released - are you able to upgrade your PRD cluster to that?

I can work on that one, yes

**Comment by grzesuav** [comment] 2020-02-26 21:30
Only mention on java bugs is to https://bugs.openjdk.java.net/browse/JDK-8182740 which seems to be fixed

**Comment by rhollencamp** [comment] 2020-02-26 21:48
AdoptOpenJDK 11.0.6 upgrade made no difference

**Comment by grzesuav** [comment] 2020-02-26 23:04
@rhollencamp when you run with `-XX:+PrintFlagsFinal` can you post all flags with default values ? I want to check if this is related to openjdk issue I mentioned above

**Comment by rhollencamp** [comment] 2020-02-27 23:03
@grzesuav 
[46-flags-final.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/4264518/46-flags-final.txt)

**Comment by grzesuav** [comment] 2020-02-29 18:12
unfortunately do not see anything related to abovementioned bug..

**Comment by rhollencamp** [comment] 2020-03-25 00:11
We moved our production cluster to centos-packaged OpenJDK and we got a slightly different SIGSEV:

    # SIGSEGV (0xb) at pc=0x00007fb5b6e2406a, pid=1070, tid=1075
    # JRE version: OpenJDK Runtime Environment (11.0.6+10) (build 11.0.6+10-LTS)
    # Java VM: OpenJDK 64-Bit Server VM (11.0.6+10-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
    # Problematic frame:
    # V  [libjvm.so+0x7c306a]  G1ConcurrentMark::mark_in_next_bitmap(unsigned int, oopDesc*, unsigned long)+0x2a
    ...
    Stack: [0x00007fb5b4f0a000,0x00007fb5b500a000],  sp=0x00007fb5b5007660,  free space=1013k
    Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
    V  [libjvm.so+0x7c306a]  G1ConcurrentMark::mark_in_next_bitmap(unsigned int, oopDesc*, unsigned long)+0x2a
    V  [libjvm.so+0x7f8c47]  void G1ParCopyClosure<(G1Barrier)0, (G1Mark)1>::do_oop_work<unsigned int>(unsigned int*)+0x137
    V  [libjvm.so+0xc0056c]  OopMapSet::oops_do(frame const*, RegisterMap const*, OopClosure*)+0x24c
    V  [libjvm.so+0x78c979]  frame::oops_do_internal(OopClosure*, CodeBlobClosure*, RegisterMap*, bool)+0x99
    V  [libjvm.so+0xe8db56]  JavaThread::oops_do(OopClosure*, CodeBlobClosure*)+0x196
    V  [libjvm.so+0xe92dc8]  Threads::possibly_parallel_threads_do(bool, ThreadClosure*)+0xa8
    V  [libjvm.so+0xe93637]  Threads::possibly_parallel_oops_do(bool, OopClosure*, CodeBlobClosure*)+0x37
    V  [libjvm.so+0x7f901c]  G1RootProcessor::process_java_roots(G1RootClosures*, G1GCPhaseTimes*, unsigned int)+0xbc
    V  [libjvm.so+0x7f97d7]  G1RootProcessor::evacuate_roots(G1ParScanThreadState*, unsigned int)+0x77
    V  [libjvm.so+0x7ae212]  G1ParTask::work(unsigned int)+0x122
    V  [libjvm.so+0xf2ee65]  GangWorker::loop()+0x55
    V  [libjvm.so+0xe95585]  Thread::call_run()+0x155
    V  [libjvm.so+0xc1a548]  thread_native_entry(Thread*)+0xf8

**Comment by aahlenst** [comment] 2020-03-25 06:44
If you are having problems with non AdoptOpenJDK builds, we are not really in a position to help. Either reach out to your vendor or, if you are confident the problem is in OpenJDK, reach out to the jbs channel on our [Slack](https://adoptopenjdk.net/slack.html) workspace and ask someone to report it to [JBS](https://bugs.openjdk.java.net/secure/Dashboard.jspa).

**Comment by karianna** [comment] 2020-03-25 14:00
@rhollencamp  - I beleive we've seen this fixed in 11.0.7 nightlies from upstream.  You can try from adoptopenjdk.net (look for nightly builds of 11)

**Comment by rhollencamp** [comment] 2020-04-20 14:53
11.0.7 does not help; I'll reach out to jbs

    # SIGSEGV (0xb) at pc=0x00007faafb90e71a, pid=24376, tid=24447
    # JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10)
    # Java VM: OpenJDK 64-Bit Server VM (11.0.7+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
    # Problematic frame:
    # V  [libjvm.so+0x7c971a]  G1ParCopyClosure<(G1Barrier)0, (G1Mark)1>::do_oop(unsigned int*)+0x22a

**Comment by jerboaa** [comment] 2020-04-20 15:25
@rhollencamp I don't see a reproducer. Is there none or am I blind?

**Comment by rhollencamp** [comment] 2020-04-20 18:10
@jerboaa we have not been able to reproduce the issue; we just observe it happening in our  production environment (maybe twice a day across a cluster of ~150 JVMs)

**Comment by aahlenst** [comment] 2020-05-30 11:57
As it stands, we cannot work on it. We'll reopen if we get instructions to reproduce.

**Closed by aahlenst** 2020-05-30 11:57 UTC
Labels: To Be Reported Upstream, Waiting on OP, bug

**Comment by HamidOsouli** [comment] 2020-12-07 23:05
Anyone having this issue running on docker ?

**Comment by nE0sIghT** [comment] 2021-06-18 15:18
> Anyone having this issue running on docker ?

We have under high load
