### ISSUE TITLE
JVM crashing Randomly

### ISSUE THREAD

**Issue by Irgendwer01** [AdoptOpenJDK/openjdk-support#164] opened 2020-08-14 22:54 UTC
## Summary
JVM is crashing randomly.
## Steps to reproduce
1. doing something with Java
2. wait for crash
## Expected results
not crashing 
## Actual results
crashing with very weird log
## Triaging info
Java version:
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.262-b10, mixed mode)

What is your operating system and platform?
Debian 10 Buster  AMD FX(tm)-4300 Quad-Core Processor @ 3.8GHZ 4 cores 
8GB RAM Nvidia Geforce GTX 750
How did you install Java?
via the tar.gz

Did it work before?
No

Did you test with other Java versions?
yes
[hs_err_pid12019.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5077698/hs_err_pid12019.log)

**Comment by aahlenst** [comment] 2020-08-15 06:38
> doing something with Java

We need a piece of code to run to trigger the crash. "Doing something" isn't sufficient because we and others do a lot of somethings and it didn't crash.

> Did you test with other Java versions?
> yes

What versions did you test with? What was the outcome?

**Comment by Irgendwer01** [comment] 2020-08-15 19:22
im able to reproduce it with almost any Java Application, mostly Modded Minecraft (Forge) http://minecraft.net/ https://files.minecraftforge.net/ and i have really no idea which Java versions i used before.

**Comment by aahlenst** [comment] 2020-08-15 20:23
Well, it looks like you're using AdoptOpenJDK's Debian package. Did you use that before or did you use something different, for example Debian's package or Oracle JDK?

To be sure that the problem still exists: Can you please upgrade to 8u265 with apt? And if the crash still occurs, could you test with https://adoptopenjdk.net/upstream.html?variant=openjdk8&jvmVariant=hotspot?

> im able to reproduce it with almost any Java Application, mostly Modded Minecraft (Forge)

I'm not familiar with Minecraft. What version do I need to install? What do I need to do in Minecraft? I'm looking for something like "Start Level 1, do nothing, wait a minute".

**Comment by Irgendwer01** [comment] 2020-08-15 23:01
im using Hotspot already and im not able to reproduce if i using this JVM: https://www.graalvm.org/ , it just happens randomly there is nothing i do that cause it in Minecraft

**Comment by aahlenst** [comment] 2020-08-16 05:49
GraalVM is a seaparte codebase. So while this is good for you, it does not help.

https://adoptopenjdk.net/upstream.html?variant=openjdk8&jvmVariant=hotspot is a build by the OpenJDK project. Crashes need to be confirmed with their build, otherwise we cannot report the problem.

The crash dump indicates that the problem is in the GC code. GC by nature has some randomness attached because it is triggered by memory pressure. But just triggering GC is not enough, otherwise we had this crash while testing the binaries. Alternatively, does it happen with another application in a more predictable manner? And again, what can I do to reproduce it lokally, be it with Minecraft or another application?

**Comment by Irgendwer01** [comment] 2020-08-16 10:01
it just happens after some hours of play time, there is nothing i do that cause it immadiently im playing with different mod only that was not changes is minecraft and the libraries and i get it very rarely with other applications, if it helps i have ZRam installed on my RAM.

**Comment by aahlenst** [comment] 2020-08-16 10:07
Can you test with disabled zRAM?

**Comment by Irgendwer01** [comment] 2020-08-16 11:07
i am not able to reproduce the problem with a Swap on a partition on my HDD, it looks like its an problem with Swap as an file as im able to reproduce it under windows too.

**Comment by Irgendwer01** [comment] 2020-08-16 11:18
Only problem is my HDD has an too slow Read and Write speed to be useable as Swap

**Comment by aahlenst** [comment] 2020-08-17 10:19
I wrote a small programs that exhaused the physical memory, occupied a good part of the swap space and then produced a lot of garbage to create memory pressure. I could not reproduce the problem with a swap file on Linux. So either a more complex memory layout is required or something else is causing it.

**Comment by Irgendwer01** [comment] 2020-08-17 13:14
should i try Disabling Memory Remapping?

**Comment by aahlenst** [comment] 2020-09-10 13:00
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-09-10 13:00 UTC
Labels: Waiting on OP, bug, not reproducible
