### ISSUE TITLE
com.sun.jndi.ldap.object.disableEndpointIdentification stop working in JDK11

### ISSUE THREAD

**Issue by leiwang1001100** [AdoptOpenJDK/openjdk-support#132] opened 2020-06-23 07:47 UTC
* **Platform and architecture**: Linux x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

* **Variant e.g. HotSpot or OpenJ9**:

* **Have you tested it with other vendors' java**: No

* **Steps to reproduce**:

* **Error messsage and/or description of what is not working as expected**: `com.sun.jndi.ldap.object.disableEndpointIdentification=true` setting stop working. The same setting works in AdoptOpenJDK **1.8.0_202**

This was helped us to ignore the SSL certificate mismatch issue. 
`javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching ...`

**Comment by karianna** [comment] 2020-06-23 10:20
@leiwang1001100 can you try with the adoptopenjdk.net/upstream.html build please?

**Comment by aahlenst** [comment] 2020-06-23 10:41
It's still in [OpenJDK 11](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/584b3cdc0f09cb71aa34e1aaa1bf050b199c145f/src/java.naming/share/classes/com/sun/jndi/ldap/Connection.java#L168-L169) and [15](https://github.com/AdoptOpenJDK/openjdk-jdk15/blob/master/src/java.naming/share/classes/com/sun/jndi/ldap/Connection.java#L168-L169. So please provide a minimal example that reproduces the problem.

**Comment by aahlenst** [comment] 2020-07-02 07:40
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed** 2020-07-02 07:41 UTC
Labels: Waiting on OP
