### ISSUE TITLE
AdoptOpenJDK 11.0.10+9 Crashes

### ISSUE THREAD

**Issue by kullwindergit** [AdoptOpenJDK/openjdk-support#259] opened 2021-02-15 15:58 UTC
```
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdf88961353, pid=1121, tid=1185
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.10+9, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# J 9114 c2 com.sun.crypto.provider.AESCrypt.implEncryptBlock([BI[BI)V java.base@11.0.10 (953 bytes) @ 0x00007fdf88961353 [0x00007fdf88961000+0x0000000000000353]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /opt/apps/core.1121)
#
# An error report file with more information is saved as:
# /opt/apps/hs_err_pid1121.log
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
```

**Comment by aahlenst** [comment] 2021-02-15 16:03
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that triggers the problem.

**Comment by kullwindergit** [comment] 2021-02-15 16:12
using AdoptJDK version 11.0.10+9 as a jvm for container apache tomcat 9.0.39 for one of my java application deployed in the tomcat. After few hours of usage, my container crashes with above error in catalina.log of apache tomcat.
Attaching another error file.

[hs_err_pid1121.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5982746/hs_err_pid1121.log)

**Comment by aahlenst** [comment] 2021-02-15 16:17
Thanks for the report. But again, nobody can help without code that reproduces the problem.

If it happens after some hours, this might point to a memory problem. Check your memory with memtest86+ or see if it happens on another machine.

**Comment by fasatrix** [comment] 2021-02-27 03:01
@aahlenst just build and run this docker and you will see the problem
https://github.com/jenkinsci/docker/blob/master/11/alpine/hotspot/Dockerfile

**Comment by aahlenst** [comment] 2021-02-27 11:12
@fasatrix Please provide exact steps to reproduce, otherwise that turns into a wild-goose chase.

**Comment by fasatrix** [comment] 2021-02-27 20:36
> @fasatrix Please provide exact steps to reproduce, otherwise that turns into a wild-goose chase.

@aahlenst here the link to a rep with some instructions , hopefully that will be it?
https://github.com/fasatrix/jenkins-on-docker

Thanks

**Comment by aahlenst** [comment] 2021-02-27 20:52
That link gives me a 404.

**Comment by fasatrix** [comment] 2021-02-27 21:51
> That link gives me a 404.

try now I made it public @aahlenst

**Comment by aahlenst** [comment] 2021-02-28 13:00
@fasatrix You're wrong here. https://github.com/AdoptOpenJDK/openjdk-docker/issues/520 is your issue.

**Comment by aahlenst** [comment] 2021-03-01 11:57
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2021-03-01 11:57 UTC
Labels: Waiting on OP
