### ISSUE TITLE
Missing OpenJDK 8 Release Notes

### ISSUE THREAD

**Issue by daylicron** [AdoptOpenJDK/openjdk-support#54] opened 2020-02-11 10:21 UTC
* **Platform and architecture (e.g. Linux/x64**:
All
* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
8u242
* **Variant e.g. HotSpot or OpenJ9**:
-
* **Have you tested it with other vendors' java**:
-
* **Steps to reproduce**:
-
* **Error messsage and/or description of what is not working as expected**:
Hey there,
https://adoptopenjdk.net/release_notes.html does not list the release notes for the available version 8u242. 

I would like to verify that the recently published Oracle Java CPU issues are fixed in this release.

Cheers
Dennis

**Comment by karianna** [comment] 2020-02-12 03:19
Duplicate of https://github.com/AdoptOpenJDK/openjdk-website/issues/673

**Closed** 2020-02-12 03:19 UTC
Labels: duplicate
