### ISSUE TITLE
unable to configure app.classpath in mac os dmg package apps/X.cfg file

### ISSUE THREAD

**Issue by eitzenbe** [AdoptOpenJDK/openjdk-support#96] opened 2020-04-30 22:29 UTC
* **Platform and architecture (e.g. Linux/x64**: Mac OS

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)

* **Variant e.g. HotSpot or OpenJ9**:
Hotspot

* **Have you tested it with other vendors' java**:
no

* **Steps to reproduce**:
use jpackager on Mac OS to create a dmg package. the app.classpath entry is always empty and there is no configuration option to change the value of this property. 

* **Error messsage and/or description of what is not working as expected**:
I have an app that utilizes JNA and for Mac OS (not needed on Windows) I need to pass in an additional class path to the java to locate the JNA native libs successfully on Mac OS
Using "-cp pathtojar" in the apps/XXX.cfg java options does not help. However setting the property app.classpath does.
But there is no cmdlimd parameter for packager to do so

**Comment by karianna** [comment] 2020-05-01 12:40
Is suspect this is a duplicate of #97

**Comment by eitzenbe** [comment] 2020-05-01 14:42
> Is suspect this is a duplicate of #97

Doubt so, i dont do any signing and the app starts up nicely IF i add the classpath to the jna.jar to the app.classpath property in the app cfg file

**Comment by andrew-m-leonard** [comment] 2020-05-01 18:22
is this related ? https://bugs.openjdk.java.net/browse/JDK-8237490
worth searching there for jpackager

**Comment by eitzenbe** [comment] 2020-05-01 20:03
Please accept that this is NOT about signing! As I stated when setting the app.classpath property in the app cfg file all works, so I am NOT into signing anything but into HOW can I configure jpackager to set this property in the process of building the dmg?

**Comment by karianna** [comment] 2020-05-01 20:53
@eitzenbe Hmm, this seems to be an issue with the upstream packager.  Please report this to core-libs at openjdk.java.net

**Comment by eitzenbe** [comment] 2020-05-01 21:27
DONE  internal review ID : 9064849

**Comment by aahlenst** [comment] 2020-07-27 14:32
https://bugs.openjdk.java.net/browse/JDK-8244575

If you want to provide additionl information or if you do not agree with the upstream resolution, https://bugs.java.com/bugdatabase/faq.do#faq-6 explains how you can comment on the issue yourself.

**Closed by aahlenst** 2020-07-27 14:32 UTC
Labels: Reported to OpenJDK / JBS, mac osx
