### ISSUE TITLE
JVM crash on exit with 'pure virtual method called'

### ISSUE THREAD

**Issue by algogavin** [AdoptOpenJDK/openjdk-support#178] opened 2020-09-07 14:46 UTC
I am running a JNI program with AdoptOpenJDK-hotspot-8u265_b01, everything seem ok but it crash on exit with error "pure virtual method called,   terminate called without an active exception", please see attached for the stack trace.

Please note that, the exact same program would work if I switch to the AdoptOpenJDK-openj9.
[stack.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/5183639/stack.txt)

**Comment by aahlenst** [comment] 2020-09-07 14:57
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Furthermore, please tell us what makes you think that the problem is in AdoptOpenJDK.

**Comment by aahlenst** [comment] 2020-09-20 05:33
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-09-20 05:33 UTC
Labels: Waiting on OP
