### ISSUE TITLE
keystore and letsencrypt new CA 

### ISSUE THREAD

**Issue by ohauer** [AdoptOpenJDK/openjdk-support#226] opened 2020-12-15 16:45 UTC
Unsure where to raise something? Here are some of the common places:
**Problem description:**
I'm really not sure where to place the request so I try it here.

Until Let's Encrypt changed to new intermediate CA it was possible to access a Let's Encrypt secured web application from java, unluckily this is now no longer the case. 

I found an article that  the root CA will also change in Jan. 2021 and It would be nice if the Let's Encrypt certs can find the way into the openjdk keystore as trusted CA.

Additional Information:
https://letsencrypt.org/certificates/
https://heise.de/-4958108 (german article)

**Comment by aahlenst** [comment] 2020-12-15 18:19
Please test with one of our nightly builds: https://adoptopenjdk.net/nightly.html

They all have new trust stores. Was intended to land in time for the October updates but did not make it.

**Comment by aahlenst** [comment] 2020-12-25 11:31
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

Besides, [Let's Encrypt announced that they'll cross-sign their new root certificate](https://letsencrypt.org/2020/12/21/extending-android-compatibility.html), so there shouldn't be any problem until the January 21 updates which include our new trust store.

**Closed by aahlenst** 2020-12-25 11:31 UTC
Labels: Waiting on OP
