### ISSUE TITLE
APPCRASH in java.exe (AdoptOpenJDK)(build 1.8.0_252-b09)

### ISSUE THREAD

**Issue by Sandygg** [AdoptOpenJDK/openjdk-support#162] opened 2020-08-08 17:30 UTC
## APPCRASH in java.exe/javaw.exe

OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

Observation with version: 8.0.2650.1 and version: 8.0.2520.9

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	javaw.exe
  Application Version:	8.0.2520.9
  Application Timestamp:	5ea011fc
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.19425
  Fault Module Timestamp:	5d26b6e9
  Exception Code:	406d1388
  Exception Offset:	000000000000908c
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	831e
  Additional Information 2:	831ef0a381f1371f31e5e55ac6ced45a
  Additional Information 3:	822f
  Additional Information 4:	822f639e9daccfe5846e708c2669d241

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

## Context

Java version:
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

Your operating system and platform:
Windows 2012 R2 / 2016 x86-64"

**Comment by aahlenst** [comment] 2020-08-08 19:47
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please fill-in as much information as possible that our [issue template](https://github.com/AdoptOpenJDK/openjdk-support/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) asks for. At least share the crash dump (hs_err_pid_*.log).

**Comment by Sandygg** [comment] 2020-08-09 20:27
Trying to generate using option -XX:ErrorFile="%temp%\\hs_err_%p.log", seems not getting generated.
Attached only a crash screenshot.
![Crash](https://user-images.githubusercontent.com/1612924/89741182-c60a1100-daac-11ea-96f5-0d3896f779ea.png)

**Comment by aahlenst** [comment] 2020-08-10 06:44
Have you looked through Event Viewer for any additional information?

**Comment by Sandygg** [comment] 2020-08-10 12:42
![image](https://user-images.githubusercontent.com/1612924/89783735-10cf6b80-db35-11ea-9e4a-4ef76adb03b0.png)

Let me know if any other information is needed.

**Comment by aahlenst** [comment] 2020-08-10 12:56
We need new information, not variations of what we already have. 😄 

Options:

* Steps to reproduce. Then we can use a debugger or something else and have a look ourselves.
* Do you get a crash with java.exe, too? That might leave a trace somewhere. I'm not familiar with javaw.exe and what it does differently.

**Comment by Sandygg** [comment] 2020-08-12 04:59
Hi aahlenst,

Comments inline ...

- Steps to reproduce. Then we can use a debugger or something else and have a look ourselves.
[Comments] This is intermittent in behavior and part of UI Console tool launched using java.exe.
Any suggestions on attaching debugger.


- Do you get a crash with java.exe, too? That might leave a trace somewhere. I'm not familiar with javaw.exe and what it does differently.
[Comments] Yes, sam behavior with java.exe.

Event Log - Application
Application Error
Event ID -1000

Faulting application name: java.exe, version: 8.0.2520.9, time stamp: 0x5ea011fc
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19724, time stamp: 0x5ec5262a
Exception code: 0x406d1388
Fault offset: 0x0000000000007afc
Faulting process id: 0x53c0
Faulting application start time: 0x01d66c81cc676052
Faulting application path: C:\auto_product\tsim\pw\jre\bin\java.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 48140176-d879-11ea-85c2-0050568f3f75


Thanks,
Sandeep
FYI - Issue not present with Oracle JRE 8.
Contact - sandeep_gaike@bmc.com

**Comment by aahlenst** [comment] 2020-08-12 10:07
Is Oracle JRE roughly the same version as AdoptOpenJDK? If yes, a comparison with https://adoptopenjdk.net/upstream.html might be interesting.

https://blogs.oracle.com/poonam/windows-crash-dumps-for-java-processes explains how to attach a debugger.

**Comment by aahlenst** [comment] 2020-08-12 10:15
If other Java distributions work, there are usually two reasons for problems on Windows:

* Anti Virus software, because Oracle Java is usually on an allow list.
* DLL/compatibility problems with native components because we're on VS 2013 with 8 and most of the others still on 2010.

In case of AV software, it helps to disable it and check again.

**Comment by Sandygg** [comment] 2020-08-15 12:57
Please find comments inline...

Is Oracle JRE roughly the same version as AdoptOpenJDK?
[Almost same - Oracle JRE 8 (jre1.8.0_65) and AdoptOpenJDK 1.8.0_252-b09 ]

Anti Virus software, because Oracle Java is usually on an allow list.
[Then it should be permanent issue not intermittently reported ]  Not variations in behavior. 😄

DLL/compatibility problems with native components because we're on VS 2013 with 8 and most of the others still on 2010.
[Since the faulting application KERNELBASE.dll, whether VS version should matter here.
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19724, time stamp: 0x5ec5262a]

**Comment by aahlenst** [comment] 2020-08-15 13:20
If you really mean https://www.oracle.com/java/technologies/javase/8u65-relnotes.html, that's a huge difference. That thing is 5 years old and a lot has changed since then.

If https://adoptopenjdk.net/upstream.html?variant=openjdk8&jvmVariant=hotspot does not exhibit the problem, it indicates a build-related problem on our side.

**Comment by aahlenst** [comment] 2020-09-10 12:27
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-09-10 12:27 UTC
Labels: Waiting on OP
