### ISSUE TITLE
Crash in OpenJDK 14

### ISSUE THREAD

**Issue by abhatnagar192006** [AdoptOpenJDK/openjdk-support#246] opened 2021-01-26 07:06 UTC
This crash took place when the application was at rest. Attaching the core dump for reference.  The problematic frame shows that the thread under execution was using Java compiled code with no role of native code:

**(Attachment has the core dump details)** 
[hs_err_pid5290.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5871736/hs_err_pid5290.log)

Problematic frame:
 J 14188 c2 me.prettyprint.cassandra.service.ThriftCfDef.fromThriftList(Ljava/util/List;)Ljava/util/List; (77 bytes) @ 0x00007fedb7c8ee93 [0x00007fedb7c8e880+0x0000000000000613]

Command Line: -Dprogram.name=run-as.sh -Dprogram.name=run-as.sh -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Xms336G -Xmx336G -XX:SoftMaxHeapSize=304G -XX:+AlwaysPreTouch -XX:MaxGCPauseMillis=25 -Djava.net.preferIPv6Stack=true -XX:+UseNUMA -XX:ConcGCThreads=32 -XX:+UseStringDeduplication -XX:StringTableSize=500009 -Dio.netty.recycler.maxCapacity.default=0 -Dio.netty.allocator.type=pooled -Dio.netty.noPreferDirect=true -Dfile.encoding=iso-8859-1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9999 -Djava.rmi.server.hostname=10.72.241.72 com.rancore.pcrf.manager.PCRFManagerBootstrap

Host: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, 80 cores, 377G, PCRF APP Tunned Release 4.0.1-16052018
Time: Sun Jan 24 04:24:06 2021 IST elapsed time: 351629 seconds (4d 1h 40m 29s)

**Comment by aahlenst** [comment] 2021-01-26 07:15
14.0.1 is out of support. Please check with 15.0.2 or a nightly build of 16. We also need code to reproduce the problem.

**Comment by abhatnagar192006** [comment] 2021-01-26 07:25
Hello. 

Thanks for your response.

The code involved is provided at this link: 
https://github.com/hector-client/hector/blob/master/core/src/main/java/me/prettyprint/cassandra/service/ThriftCfDef.java#L173

This is pure java compiled code, and no native code is involved. Also, this issue does not happen every time, and is random in nature. Hence, not sure if upgrading may solve this issue or it may get reproduced readily. 

Is there something that has been fixed in 15.0.2 version regarding this condition, or is it just a support issue ? 

I believe the same condition may also be present in Open JDK 15.0.2 as well, if there is no precedence of this issue being reported in version 14.

Thanks again and regards

Aayush

**Comment by aahlenst** [comment] 2021-01-26 07:50
> The code involved is provided at this link

Thanks, but that's not what we are looking for. Please provide a small sample (class with main method) that can be independently run and triggers the problem you're experiencing. Otherwise, it might be very hard to impossible to develop and especially verify a potential fix. Considering the code looks innocent, there seems to be something else that's going on.

We also have to ensure that the problem isn't machine-specific which would point towards faulty hardware.

> This is pure java compiled code, and no native code is involved.

At the place of the crash, yes. But maybe the invalid address was created somewhere else.

> Is there something that has been fixed in 15.0.2 version regarding this condition, or is it just a support issue ?

Both. A lot of bugs got fixed. And OpenJDK does not accept reports if they cannot be reproduced with a maintained version.

**Comment by aahlenst** [comment] 2021-03-01 11:54
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2021-03-01 11:54 UTC
Labels: Waiting on OP, bug
