### ISSUE TITLE
Cassandra 3.11.4 doesn't startup with AdoptOpenJDK build 25.222-b10

### ISSUE THREAD

**Issue by NitishBangera** [AdoptOpenJDK/openjdk-support#30] opened 2019-08-13 15:54 UTC
* **Browser**:

My Java version is the following

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

I am in the process of evaluating AdoptOpenJdk so that my company moves away from Oracle's Jdk. All my java apps have been working fine but Cassandra 3.11.4 has been giving me issues during startup. 

Issues
1. The jna-4.2.2.jar which comes bundled doesn't creates the dll. When its upgraded to jna-4.5.2.jar then the jna works fine.
2. On startup, the JVM crashes with the following error

```
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [sigar-amd64-winnt.dll+0x14ed4]
```

I do understand that its outside the JVM but as soon as I shift to the following Oracle's jdk, cassandra starts up pretty fine without issues and I am able to do all the functionalities.
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

I am on hold for the migration due to this issue.

**Comment by ye** [comment] 2020-01-21 19:58
Hi I am encountering the same issues. 

```
Windows 10 Pro (Version 10.0.18363 Build 18363) x64-based PC
Apache Cassandra 3.11.4 (and 3.11.5)
OpenJDK Runtime Environment (AdoptOpenJDK)(Build 1.8.0_232_b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK build 25.232-b09, mixed mode)
```

@NitishBangera how do you upgrade the pre-bundled jna-4.2.2.jar to to 4.5.2? Or Where did you find the Windows x64 installer for upstream OpenJDK? Thanks 🙏

**Comment by lehelsipos** [comment] 2020-04-09 09:03
I have the same problem!
![cassandra_java_error](https://user-images.githubusercontent.com/50200405/78877849-c25c7400-7a51-11ea-9bcb-79af84388caf.png)

**Comment by karianna** [comment] 2020-04-09 21:42
Adding to top priority so we shift build chains this quarter if we can find the right folks.

**Comment by aahlenst** [comment] 2020-11-07 11:15
@d3r3kk Do you intend to work on it? Is there anything we can do to help?

**Comment by aahlenst** [comment] 2020-11-11 11:35
While checking whether the problem persists with the latest versions (it does), I realized that the problem is yet again Sigar: https://github.com/AdoptOpenJDK/openjdk-support/issues/22.

Sigar (a pile of C code for monitoring purposes) has long been abandoned but is still being used by Cassandra, even in the Beta 3 of Cassandra 4. Sigar is compiled against VS 2008 and works with a JDK compiled with VS 2010 (for example, upstream builds). It crashes with every JDK built with a newer VS version. After a couple of fixes, I got Sigar to compile with VS 2017 but that did not help either.

**Comment by cnstar9988** [comment] 2020-11-27 16:28
It is sigar 1.6.4 bug.
 
https://github.com/hyperic/sigar/issues/141
https://github.com/cnstar9988/sigar/commit/9e5dba8d520cca718209d93fb89a4c5daebb7655

**Comment by aahlenst** [comment] 2020-12-10 16:24
@cnstar9988 Thank you for finding the problem with Sigar. It seems to work fine, people might need the [Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package](https://www.microsoft.com/en-us/download/details.aspx?id=26999) to make Cassandra start.

Because the problem is not in AdoptOpenJDK, I'm going to close the issue. Our findings have been reported to the Cassandra folks, please follow https://issues.apache.org/jira/browse/CASSANDRA-15950 (or any linked issues) for updates.

**Closed by aahlenst** 2020-12-10 16:24 UTC
Labels: AdoptOpenJDK only

**Comment by cnstar9988** [comment] 2020-12-18 13:55
OK, it's not a AdoptOpenJDK bug.

The sigar bug affects latest windows 64 + openjdk (both Oracle JDK).
