### ISSUE TITLE
Windows client: -Dfile.encoding=UTF-8 causes Swing app to crash

### ISSUE THREAD

**Issue by maeda-a** [AdoptOpenJDK/openjdk-support#192] opened 2020-10-08 08:30 UTC
The code:

```
import javax.swing.JOptionPane;

public class Hello {
    public static void main(String args[]) {
            JOptionPane.showOptionDialog(null, "Hello", "Dialog",
                                        JOptionPane.OK_CANCEL_OPTION,
                                        JOptionPane.PLAIN_MESSAGE,
                                        null, null, null);
    }
}
```

always crashes when run by `java -Dfile.encoding=UTF-8 Hello`,
run withouut problems when run by just `java Hello`.

Windows 10 , 64 bit Build 19041 (10.0.19041.292)
AdoptOpenJDK 11.0.8+10, (no other Java tools are installed on the system.)
[hs_err_pid9656.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5346344/hs_err_pid9656.log)

**Comment by karianna** [comment] 2020-10-08 08:51
@maeda-a Can you try an adoptopenjdk.net/upstream.html build?

**Comment by aahlenst** [comment] 2020-10-08 09:35
I cannot reproduce the problem. I have to invoke it with `java -D"file.encoding=UTF-8" Hello` (extra quotes around `file.encoding`), however.

I see you're using a Japanese locale. Can you explain how I need to alter a standard Windows installation with en-US to trigger the bug?

**Comment by maeda-a** [comment] 2020-10-08 10:48
Re: upstream build
I'm trying 11.0.9+10ea, but it says it can't find jimage in java.library.path.
I just unzipped the archive, set JDK_HOME and PATH, and ran javac&java.  Will I need something more to do?

Re: en-US version
I'll try to install en-US WIndows on VirtualBox maybe tommorrow.

**Comment by maeda-a** [comment] 2020-10-08 12:22
Re: en-US version
I'll try steps in the following page
https://qiita.com/Targityen/items/1feb17ecbda7eadb60da  (in Japanese but lots of screenshots may help)

**Comment by aahlenst** [comment] 2020-11-07 11:13
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-11-07 11:13 UTC
Labels: Waiting on OP, not reproducible, question
