### ISSUE TITLE
AIX crashes 8u282 but not 8u265 

### ISSUE THREAD

**Issue by ed03875** [AdoptOpenJDK/openjdk-support#279] opened 2021-03-11 20:56 UTC
## Summary

We have seen many crashes in a number of locations. We first thought it was JIT related so we disabled  JIT and we see the same crashes, This is definitely a regression from 8u265 that is present in 8u282. 
[stacks.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/6125902/stacks.txt)
[javacore.20210302.071234.25625076.0002.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/6125905/javacore.20210302.071234.25625076.0002.txt)

## Steps to reproduce
Here is where the problem is.  There are no steps that you can duplicate we found it during automated testing and can reproduce with a subset of the test. The people who sign my pay check require I write this report sending a javacore and stacks. We have many stacks that indicate the same thing,

## Expected results
Test runs correctly 

## Actual results
Crashes is many places

## Triaging info

Java version:
This is the release that is causing issues
[root@pautoaixnext:/opt/ibm/domino/notes/latest/ibmpow/jvm/bin]#./java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
Eclipse OpenJ9 VM (build openj9-0.24.0, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20210120_953 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08)

This release works fine
[root@pautoaixnext:/opt/ibm/domino/notes/latest/ibmpow/jvm/bin]#cd ../../jvmback/bin
[root@pautoaixnext:/opt/ibm/domino/notes/latest/ibmpow/jvmback/bin]#./java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20200728_769 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)

What is your operating system and platform?
 OS Level         : AIX 7.2
2XHCPUS        Processors -
3XHCPUARCH       Architecture   : ppc64
3XHNUMCPUS       How Many       : 8
3XHNUMASUP       NUMA is either not supported or has been disabled by user

How did you install Java?
We install the entire JRE within a JVM directory in our product. 

Did it work before?
Works with 8u265 and fails with 8u272.  We can take 8u272 and place it in a previous version of our product and it will fail the same way

The Java version 

Did you test with other Java versions?
Yes see above

**Comment by pshipton** [comment] 2021-03-12 13:46
@ed03875
- you mention both 8u282 and 8u272, pls confirm 8u272 is the first build that shows the problem.
- is it possible to get us a test case that reproduces the problem?
- if not, can we get a system core file of the crash? We can't do anything from what has been provided. You can compress the system core and put it on a file sharing service. Email me directly if you don't want it public.
- there are some things you can try to help narrow down what component is causing the problem
  - run the test case with `-Xshareclasses:none` to see if the problem still reproduces
  - run the test case with `-Xint`. This disables the JIT so it will run much slower, it's not necessarily feasible to do this depending on how complicated the test case is, as the run time may be too long.

@tajila @zl-wang fyi

**Comment by ed03875** [comment] 2021-03-12 14:08
These crashes occur with 8u282 but not with 8u272.  If we move the JRE from version to version of Domino the crash moves with the JRE 
As I explained we can not supply a test case as that would require a Domino setup and automation very large 
I have sent a javacore and stacks I will send a system core I believe we have one
We have already disabled JIT as explained in my summary there was no change  
We have since found the same problem with Linux it does not happen with Windows
This is clearly a regression as we test this for every release.

**Comment by pshipton** [comment] 2021-03-12 14:35
So have you tested 8u272 or 8u275, can you confirm it doesn't crash which this version? If you haven't tried this version pls try it. It helps to narrow down the list of changes from the working to non-working build.

**Comment by ed03875** [comment] 2021-03-12 14:44
My mistake we have not tested with 27? only 282 and 265.

**Comment by ed03875** [comment] 2021-03-12 14:53
Have you looked at the stacks I supplied there are many different crashes but they all show this
fatal_error@AF35_19
Along with some other seemingly similar stacks

**Comment by pshipton** [comment] 2021-03-12 15:01
It looks like memory has been corrupted, so the stacks show places that crashed due to the corruption but don't help track what caused the corruption. The system core file allows looking at the corrupted data, which may or may not help to track down the problem.

The javacore file indicates there was a trace assert. There should be some information in the console output for the tracepoint which asserted. You could provide that if it's available, although again I don't expect it will help track the cause of the problem.

**Comment by ed03875** [comment] 2021-03-12 15:06
Do you have a site we can put this core file on ? I do not believe we have 
a public site that can be used for that purpose. 



From:   Peter Shipton ***@***.***>
To:     AdoptOpenJDK/openjdk-support ***@***.***>
Cc:     ed03875 ***@***.***>, Mention ***@***.***>
Date:   03/12/2021 10:02 AM
Subject:        Re: [AdoptOpenJDK/openjdk-support] AIX crashes 8u282 but 
not 8u265  (#279)



It looks like memory has been corrupted, so the stacks show places that 
crashed due to the corruption but don't help track what caused the 
corruption. The system core file allows looking at the corrupted data, 
which may or may not help to track down the problem.
The javacore file indicates there was a trace assert. There should be some 
information in the console output for the tracepoint which asserted. You 
could provide that if it's available, although again I don't expect it 
will help track the cause of the problem.

**Comment by pshipton** [comment] 2021-03-12 15:09
There are some sites listed here https://www.gflesch.com/elevity-it-blog/best-file-sharing-software-platforms

If you have a Linux core file we may prefer to look at that one.

**Comment by pshipton** [comment] 2021-03-12 15:11
You could also join the OpenJ9 Slack and drag and drop the compressed file to me. See "Join OpenJ9 slack" on https://www.eclipse.org/openj9/ for the invitation.

**Comment by pshipton** [comment] 2021-03-12 15:13
See also option 4 in https://blog.hubspot.com/marketing/send-large-files

**Comment by ed03875** [comment] 2021-03-12 17:39
We have tested with 8u272 and it also shows the same problem so no need to test with 275.

**Comment by ed03875** [comment] 2021-03-12 17:59
We can not use public sites with HCL data do you have a dropbox we can send this file to ?

**Comment by pshipton** [comment] 2021-03-12 18:58
No sorry. Maybe you can send it via IBM support, do you have contacts there?

**Comment by ed03875** [comment] 2021-03-12 19:25
I have tried a number of things but due to restrictions currently in place zip split is the only workable option
[core1.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6132478/core1.zip)
[core2.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6132481/core2.zip)
[core3.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6132486/core3.zip)
[core4.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6132489/core4.zip)
[core5.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6132493/core5.zip)
I will be working on a better way but for now and before I start hearing from management that I only read about in the newspapers I need to get this to you.  I hope it helps

**Comment by pshipton** [comment] 2021-03-12 21:06
Dmitri is looking at the core. While that occurs, we have a milestone 1 build for the next release. If you want to try it, maybe the problem has already been resolved.
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u292-b05_openj9-0.26.0-m1

**Comment by ed03875** [comment] 2021-03-13 20:24
We will thank you

**Comment by ed03875** [comment] 2021-03-13 20:56
So I pulled down OpenJDK8U-debugimage_ppc64_aix_openj9_8u292b05_openj9-0.26.0-m1.tar.gz
And here is where I get lost.  The bin directory contains what one would expect but there is no JVM directory so I looked into the lib directory and I find the directories I would expect to see in jre bin but without the contents I expect. I see 
libjsig.debuginfo  libjvm.debuginfo.   I was looking for .so files what I see is .debuginfo files.  I had hoped for a useable jre in the debug but what I have I do not understand. Please explain

**Comment by pshipton** [comment] 2021-03-13 22:21
The debugimage files are overlays for the JDK or JRE, and add debug symbols to help diagnose problems. It's a separate download to keep the JDK and JRE smaller.

**Comment by ed03875** [comment] 2021-03-14 12:05
Thanks for the help 
One thing that came up in discussion here.  Is there anything that has been done to the JVM that would drastically change its positioning in our address space when loaded ?  We can't help but question if this problem that looks like memory being overwritten is something that we are doing and we just have not seen it before but a change to the JVM brings it to light.

**Comment by pshipton** [comment] 2021-03-15 12:58
Hard to say, there are many changes
https://github.com/eclipse/openj9/releases/tag/openj9-0.22.0
https://github.com/eclipse/openj9/releases/tag/openj9-0.23.0

**Comment by ed03875** [comment] 2021-03-15 13:31
8u292 failed in a similar way 

################################### 
## thread 163/166 :: server pid=21955018, k-id=79233423 , pthr-id=41379 
## stack          :: k-state=wait, stk max-size=264328, cur-size=13640 
################################### 
raise.nsleep(??, ??) at 0x90000000003f4c4
sleep@AF4_1(??) at 0x90000000017d04c
OSRunExternalScript(0x12bba6060, 0x100000001) at 0x9000000088e3510
OSFaultCleanupExt(0x0, 0x100000001000, 0x0, 0x0, 0x0, 0x0) at 0x9000000088e2bb8
fatal_error@AF35_19(0xb0000000b, 0x12bba66d0, 0x12bba6420) at 0x9000000089dc3c4
nextSlot__33GC_ConstantPoolObjectSlotIteratorFv@AF2_1(??, ??) at 0x90000001452ba44
nextSlot__16GC_ClassIteratorFv(??) at 0x90000001452b6d8
scavengeIndirectObjectSlots__20MM_ScavengerDelegateFP22MM_EnvironmentStandardP8J9Object(??, ??, ??) at 0x9000000145bc324
scavengeRememberedSetList__12MM_ScavengerFP22MM_EnvironmentStandard(??, ??) at 0x9000000145a6228
workThreadGarbageCollect__12MM_ScavengerFP22MM_EnvironmentStandard(??, ??) at 0x90000001459fbc0
run__23MM_ParallelScavengeTaskFP18MM_EnvironmentBase(??, ??) at 0x9000000145d2a90
workerEntryPoint__21MM_ParallelDispatcherFP18MM_EnvironmentBase(??, ??) at 0x9000000146233ac
dispatcher_thread_proc2__FP14OMRPortLibraryPv(??, ??) at 0x9000000146224fc
omrsig_protect(??, ??, ??, ??, ??, ??, ??) at 0x900000012e8be48
dispatcher_thread_proc(??) at 0x90000001462312c
thread_wrapper(??) at 0x900000012ef975c

**Comment by ed03875** [comment] 2021-03-15 13:45
No core file generated

**Comment by ed03875** [comment] 2021-03-15 17:28
Is there a way for me to get at the nightly or milestone builds for earlier releases  so we can help narrow this down ? We know the problem exists in 272 so a build between 262 and 272 might help.  Is there a way to get at m1 or m2 for 272 ?  I have looked but I don't seem to be able to get one.  I must be missing something

**Comment by pshipton** [comment] 2021-03-15 18:26
The milestone builds are as follows.
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u272-b08_openj9-0.23.0-m1
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u272-b09_openj9-0.23.0-m2

You can find nightly builds here https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9
Look for builds prior to 2020-09-24. This date should be quite close to the branch for 0.23.0 (m1). You can go back to 2020-06-05 which is about when the 0.21.0 release (u262/u265) was branched.

**Comment by dmitripivkine** [comment] 2021-03-15 19:42
@ed03875 We need more cores to look. 

In the core provided in https://github.com/AdoptOpenJDK/openjdk-support/issues/279#issuecomment-797702623 memory has been corrupted (zeroed). Most possible case that previous memory allocation has been written out-of bound. In this core previous allocation belong to JIT Data Cache (see https://github.com/eclipse/openj9/issues/12207#issuecomment-799697007)

If we look to different core(s) and see the same pattern (previous allocation JIT Data Cache) it will help obviously

**Comment by ed03875** [comment] 2021-03-15 20:11
We tested 8u272 milestone one and it crashed.  I am working on getting you another core file for analysis.  We have 32 crashes and only 4 core files which is unfortunate

**Comment by ed03875** [comment] 2021-03-15 20:12
We have a core where JIT is turned off

**Comment by dmitripivkine** [comment] 2021-03-15 20:19
Any core will help in this situation. Crash points are meaningless due random corruption of memory (just victims), so we need to find pattern.
Cores for Linux are preferable, you AIX is not configured to include Read Only segment to the core, so all strings (names) are unavailable.

**Comment by ed03875** [comment] 2021-03-15 20:39
I will see if we can crash and get a core from linux right now all we have is AIX
[core1.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144294/core1.zip)
[core2.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144295/core2.zip)
[core3.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144297/core3.zip)
[core4.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144298/core4.zip)
[core5.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144300/core5.zip)
We are going to send you the cores we have in the hope something shows a pattern

**Comment by ed03875** [comment] 2021-03-15 20:53
Here is another one 
[core1.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144376/core1.zip)
[core2.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144380/core2.zip)
[core3.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144382/core3.zip)
[core4.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144383/core4.zip)
[core5.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144385/core5.zip)
[core6.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144387/core6.zip)
[core7.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144389/core7.zip)

**Comment by pshipton** [comment] 2021-03-15 21:00
> We have a core where JIT is turned off

This one would be useful, as the problem cannot be related to "JIT Data Cache" since it occurs with JIT disabled.

**Comment by ed03875** [comment] 2021-03-15 21:03
Here is another one from AIX trying to get you a Linux core 
[core1.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144482/core1.zip)
[core2.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144485/core2.zip)
[core3.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144487/core3.zip)
[core4.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144490/core4.zip)
[core5.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144492/core5.zip)
[core6.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6144494/core6.zip)

**Comment by ed03875** [comment] 2021-03-15 21:05
The core from March 11 has JIT turned off

**Comment by ed03875** [comment] 2021-03-15 21:06
That would be the last one I sent you

**Comment by dmitripivkine** [comment] 2021-03-16 13:55
@ed03875 Are you aware about https://www.ibm.com/support/pages/apar/IJ30808? This is specific for AIX 7.2.5 and this is AIX malloc() problem. I can see from the core you are using AIX 7.2, is it a chance this is 7.2.5?

**Comment by ed03875** [comment] 2021-03-16 14:07
Thank you I was not aware of the issue but we are looking into it now.  Unfortunately we experience the same crash with Linux is there a problem there also ?

**Comment by dmitripivkine** [comment] 2021-03-16 14:25
I guess may be on Linux there is another problem. Would you please send me core for Linux as soon as you got one?

**Comment by dmitripivkine** [comment] 2021-03-16 15:04
Also using https://www.eclipse.org/openj9/docs/tool_jextract/ might help to collect required libraries for debugging. For example in the cores sent to us two of them have crashes in custom or system libraries (for example `/opt/ibm/domino/notes/latest/ibmpow/libnotes_r.a`)

**Comment by ed03875** [comment] 2021-03-16 15:28
We are trying to get you a Linux core without success so far but people are actively working on it

**Comment by ed03875** [comment] 2021-03-16 15:30
Responding to the AIX version question. The test system we are using is at 7.2 TL 1 so it's not that high of level

**Comment by dmitripivkine** [comment] 2021-03-16 18:05
I looked to four cores so far, all for AIX. All of them have assertions/crashes at random places (typical for memory corruption). Another common symptom is number of problems with classes (discovered by GC Check). Most common is `ramStatics` is NULL but `romClass->objectStaticCount` is one (can it be explained by memory corruption)?
This is summary:

- https://github.com/AdoptOpenJDK/openjdk-support/issues/279#issuecomment-797702623
There is assertion in Port library at free memory (bad j9memtag). Looks like area of memory has been zeroed. Previous allocation (with zeroed closing tag) is 2m JIT Data Cache

- https://github.com/AdoptOpenJDK/openjdk-support/issues/279#issuecomment-799735838
Assertion in `BytecodeInterpreter.hpp:7979: ((0 ))`. I guess this another victim of random memory corruption.

- https://github.com/AdoptOpenJDK/openjdk-support/issues/279#issuecomment-799744793
Segmentation error in `/opt/ibm/domino/notes/latest/ibmpow/libnotes_r.a`
There is not much I can do without custom library

- https://github.com/AdoptOpenJDK/openjdk-support/issues/279#issuecomment-799750503
**This core does not have JIT running**
Segmentation error at (?):
```
c-stack:
malloc_y(0x1190540f0, 0x0, 0x9001000a007d620, 0x0, 0x0, 0x4af0103, 0x0, 0xb7a9010c9f92080) at 0x90000000004b214 [untrusted: /usr/lib/libc_r.a(shr_64.o)]
malloc_common@AF104_87(??) at 0x90000000002e668 [untrusted: /usr/lib/libc_r.a(shr_64.o)]
_cleanup_push@AF79_34(??, ??, ??, ??) at 0x9000000005a3dd8
localtime64_tz_r(??, ??, ??) at 0x90000000009d048 [untrusted: /usr/lib/libc_r.a(shr_64.o)]

0x90000000004b214 (malloc_y+0xdf4) f8640000            std   r3,0x0(r4)
```
@tajila FYI

**Comment by ed03875** [comment] 2021-03-16 19:12
More information for you daily builds August 12th and July 29 also crash 
core from July 29 daily build 
[core.server.12255738.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6151659/core.server.12255738.zip)

**Comment by dmitripivkine** [comment] 2021-03-16 19:23
Unfortunately I can not open this core ("No JRE"). I guess this file is truncated, corrupted or has source other than JVM

**Comment by ed03875** [comment] 2021-03-16 19:35
That is unfortunate but explains why it was so small
Will try for another

**Comment by pshipton** [comment] 2021-03-16 22:58
A little late, but if it helps I've figured out you can add files here
https://ibm.ent.box.com/f/15280665b3554efca921efb919634cd6

and Dmitri or others can access them via https://ibm.box.com/s/5tfl1f5sspwaep4qef3gdlaz73ej5d9e

**Comment by ed03875** [comment] 2021-03-17 16:42
Well it has been a long several days but the good news is we finally found the problem and it is in our code. Looks like C++ objects were being instantiated by C in two places that we were unaware of.  Thank you very much for your help.  We are sorry we took your time on this one but initially we were crashing and every crash had the JVM in the stack and the stack was a mess.

**Comment by dmitripivkine** [comment] 2021-03-17 17:01
You are welcome. Thank you for using OpenJ9

**Closed** 2021-03-18 14:11 UTC
Labels: bug, not a jvm bug
