### ISSUE TITLE
Eclipse cannot start with 11.0.6 on MacOS, symlink missing

### ISSUE THREAD

**Issue by heklaz** [AdoptOpenJDK/openjdk-support#74] opened 2020-03-14 08:39 UTC
* **Platform and architecture (e.g. Linux/x64**:
MacOS 10.14.6

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
"11.0.6" 2020-01-14

* **Variant e.g. HotSpot or OpenJ9**:
HostSpot

* **Have you tested it with other vendors' java**:
Oracle jdk-11.0.5.

* **Steps to reproduce**:
Attempt to start eclipse (2019-12)

* **Error messsage and/or description of what is not working as expected**:
 ~/Applications/Eclipse.app/Contents/MacOS/eclipse 
Error: could not find libjava.dylib
Failed to GetJREPath()

Turned out that the description in https://github.com/corretto/corretto-8/issues/18 seemed to help solve the problem. 

Re-creating the symlink solved the problem

sudo ln -sf /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/jli/libjli.dylib /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/MacOS

**Comment by aahlenst** [comment] 2020-03-14 11:50
Duplicate of #52. Will be fixed with 11.0.7, due mid of April.

**Closed** 2020-03-16 11:41 UTC
Labels: duplicate
