### ISSUE TITLE
System.load throws UnsatisfiedLinkError

### ISSUE THREAD

**Issue by AFrappeM** [AdoptOpenJDK/openjdk-support#134] opened 2020-06-26 00:15 UTC
OS Version: **Windows 2019 Server** 
AdoptOpenJDK Version: **OpenJDK14U-jdk_x64_windows_hotspot_14.0.1_7**
Symptoms: 
When running a java code with System.load(path), where the path is valid, pointing to a dll, a UnsatisfiedLinkError is thrown. 

The library in the example is https://github.com/java-native-access/

**Comment by aahlenst** [comment] 2020-06-26 07:11
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aahlenst** [comment] 2020-07-06 07:02
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed** 2020-07-08 06:41 UTC
Labels: Waiting on OP, wontfix
