### ISSUE TITLE
Font rendering got uglier when passing from 11.0.5+10 to 11.0.6+10

### ISSUE THREAD

**Issue by negora** [AdoptOpenJDK/openjdk-support#50] opened 2020-02-04 08:12 UTC
* **Platform and architecture (e.g. Linux/x64)**:
Debian 10 (Buster)
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

* **Java version (from "java --version", e.g. 1.8.0_181, 11.0.4+11 etc.)**:
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

* **Variant (e.g. HotSpot or OpenJ9)**:
HotSpot.

* **Have you tested it with other vendors' java**:
Yes.

* **Steps to reproduce**:
Run any application that uses AWT/Swing, such as NetBeans IDE.

* **Error messsage and/or description of what is not working as expected**:
Font rendering has gotten uglier after the upgrade from version 11.0.5+10 to 11.0.6+10. Text looks like too light or thin.

One of the reasons why I used the compilation from AdoptOpenJDK, was that the font rendering was superior to the one from Debian. However, it has turned uglier after the upgrade from version 11.0.5+10 to 11.0.6+10. Right now, it looks like as bad as Debian's: too light or thin.

I've tested AdoptOpenJDK 13.0.1+9 and 13.0.2+8, and the result is also an ugly rendering :( .

With 11.0.6+10, texts look like too light:
![openjdk-11 0 6+10](https://user-images.githubusercontent.com/2098654/73725807-767a0f80-472e-11ea-94d3-0602fa739a98.png)

With 11.0.5+10, texts look like a lot better:
![openjdk-11 0 5+10](https://user-images.githubusercontent.com/2098654/73725808-7712a600-472e-11ea-96f8-c66f8d9b01e6.png)

This problem is even worse when you use a dark background, which I do when I write code.

Thank you.

**Comment by dvalter** [comment] 2020-02-23 03:27
This bug is caused by
1. Change of Freetype interpreter version from default (v40 almost everywhere) to v35 (outdated, looks awful)
2. Unability to write a correct C code for that: for instance this code makes an absolutely broken check for a override environment variable, so `export FREETYPE_PROPERTIES="truetype:interpreter-version=40"` should help, but it doesn't either

Code:
https://github.com/openjdk/jdk11u/blame/master/src/java.desktop/share/native/libfontmanager/freetypeScaler.c#L269

**Comment by negora** [comment] 2020-04-15 11:58
@dvalter First of all, apologizes for the long delay of my answer. And thank you for such a valuable information.

So, Is there no way to force the use of one interpreter or the other in Linux? After reading the bug report [#8217731](https://bugs.openjdk.java.net/browse/JDK-8217731), I understand the motivation to use the old interpreter by default. It's a fair reason. However, in those applications that don't allow to change the font family of the UI (such as NetBeans IDE or WizTools.org RESTClient), the text is hard to read.

PS: [The new v40 TrueType interpreter mode](https://www.freetype.org/freetype2/docs/subpixel-hinting.html) is an interesting read, by the way.

**Comment by dvalter** [comment] 2020-04-15 15:32
@negora 
It could be fixed easily by swapping `strstr` arguments, but somehow some of OpenJDK devs are okay with closing [this bug](https://bugs.openjdk.java.net/browse/JDK-8239091?jql=labels%20%3D%20freetype) and duplicates with *"fixed in 15"*.

Hopefully one day they fix it, but now there's a workaround:
set environment variable `FREETYPE_PROPERTIES` to `interpreter-version` (`FREETYPE_PROPERTIES=interpreter-version`). This value will trick broken check in OpenJDK and then FreeType should load defaults. It works for me now and I hope it will with most of modern FreeType versions that use v40 by default.

**Comment by negora** [comment] 2020-04-16 06:08
@dvalter Thank you. That's another interesting bug report. I'll keep an eye on it. It's a shame that one can't subscribe to JDK Bug System JIRA without being an OpenJDK developer.

> set environment variable `FREETYPE_PROPERTIES to interpreter-version`

You made my day! :+1: I've tested it with NetBeans IDE 11.3 and OpenJDK 14, and it works flawlessly. Also with OpenJDK 11, of course. Thanks a lot.

**Comment by aahlenst** [comment] 2020-07-27 14:34
This should be fixed with 11.0.8.

**Closed by aahlenst** 2020-07-27 14:34 UTC
Labels: Reported to OpenJDK / JBS, bug

**Comment by negora** [comment] 2020-08-04 11:56
I've tested the version 11.0.8, both from AdoptOpenJDK and Debian, and the variable `FREETYPE_PROPERTIES='truetype:interpreter-version=40'` is interpreted correctly now. Thank you! :+1:

**Comment by taasjord** [comment] 2020-09-05 13:10
Having the same issue with Netbeans, fonts look ugly exactly like that image above. The variable FREETYPE_PROPERTIES with 11.0.8 did not help anything for me. 

What is it with Java and the continuous problems with font rendering? Ever since Oracle Java 8, OpenJDK 12 is the only version I ever got proper fonts with. Tested OpenJDK 11, 13, 14, 15, 16 and all have the same font issues.

**Comment by negora** [comment] 2020-11-30 09:48
@taasjord I've just tested OpenJDK 11.0.9 (compiled by Debian) and OpenJDK 15.0.1 (compiled by AdoptOpenJDK), and both work well with that option.

Have you tried exactly with this value: `FREETYPE_PROPERTIES='truetype:interpreter-version=40'`?
