### ISSUE TITLE
Customer is getting SIGSEGV with AdoptOpenJDK11

### ISSUE THREAD

**Issue by psarkarping** [AdoptOpenJDK/openjdk-support#263] opened 2021-02-18 18:46 UTC
## Summary
The customer is using the following environment:
Oracle linux server 7.7
PingDirectory 8.1.0.2
AdoptOpenJDK 11.0.8+10
Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.8+10, mixed mode, tiered, g1 gc, linux-amd64)

We have a customer running PingDirectory server in production. The customer gets the following segmentation fault with the problematic frame being Problematic frame J27430 c2. The JRE is below:
```
#
# SIGSEGV (0xb) at pc=0x00007fa56d174b29, pid=9027, tid=27976
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.8+10, mixed mode, tiered, g1 gc, linux-amd64)
# Problematic frame:
# J 27430 c2 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(J)J java.base@11.0.8 (181 bytes) @ 0x00007fa56d174b29 [0x00007fa56d174260+0x00000000000008c9]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/ldap/instances/extusrprd/bin/hs_err_pid9027.log
Compiled method (c2) 1953461698 157455 ! 4 com.unboundid.directory.server.replication.server.GatewayState::isGateway (27 bytes)
total in heap [0x00007fa56c354a90,0x00007fa56c355228] = 1944
relocation [0x00007fa56c354c08,0x00007fa56c354c60] = 88
main code [0x00007fa56c354c60,0x00007fa56c354ec0] = 608
stub code [0x00007fa56c354ec0,0x00007fa56c354f08] = 72
oops [0x00007fa56c354f08,0x00007fa56c354f10] = 8
metadata [0x00007fa56c354f10,0x00007fa56c354f50] = 64
scopes data [0x00007fa56c354f50,0x00007fa56c355078] = 296
scopes pcs [0x00007fa56c355078,0x00007fa56c355188] = 272
dependencies [0x00007fa56c355188,0x00007fa56c355198] = 16
handler table [0x00007fa56c355198,0x00007fa56c3551f8] = 96
nul chk table [0x00007fa56c3551f8,0x00007fa56c355228] = 48
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
```
## Steps to reproduce

Unfortunately, I don't think this bug is something that can be minimally and easily reproduced (though I can ask if the customer can easily reproduce it somehow)...is there any way we may still get some support in this ticket? We are trying to determine if there is a bug with PingDirectory server, but it would be very helpful if we could get some help from AdoptOpenJDK, because the error seems to be JVM-related. I'd be happy to attach any log files or answer any questions.

**Comment by aahlenst** [comment] 2021-02-18 19:27
Attach at least hs_err_pid9027.log. Upgrading to the latest version (11.0.10) is always good, too.

**Comment by psarkarping** [comment] 2021-02-18 19:48
[hs_err_pid9027.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6005489/hs_err_pid9027.log)

**Comment by aahlenst** [comment] 2021-02-18 20:58
Someone reported a similar problem at OpenJDK a while ago: https://bugs.openjdk.java.net/browse/JDK-8258982. The resolution was to update PingDirectory.

**Comment by psarkarping** [comment] 2021-02-18 23:10
I found the Ping ticket (STAGING-11780) that resulted in https://bugs.openjdk.java.net/browse/JDK-8258982! Unfortunately, a few days after JDK-8258982 was opened and the customer had upgrade, they started seeing the crash again. When they went back to Java 8, the crashes stopped happening. Right now, the customer for this ticket is not willing to go back to Java 8. I can try suggesting they upgrade to PingDirectory 8.2, but I'm concerned they will still crash.

**Comment by aahlenst** [comment] 2021-02-19 06:45
The usual suspects in such cases are:

* Misbehaving native code
* Faulty RAM
* A problem in the JDK's GC or optimizer

The first two options are the most common problems and are rather easy to find. Faulty RAM can be detected with memtest86+ or by running the software on a second machine. That the problem went away when one customer went back to 8 makes faulty RAM less probable, so I'd focus on misbehaving native code.

Tracking down problems in the JDK is significantly harder. You basically need code that triggers the problem reliably, even if that means it only fails twice per 1000 iterations. Otherwise it's unlikely that the cause can be found and fixed. If that's not feasible, try upgrading and hope that it goes away. If 11.0.10 does not help, 15.0.2 might.

I don't know whether Oracle's (paid) support has special skills to track down such a problem. I've never seen them in action.

**Comment by aahlenst** [comment] 2021-03-14 12:53
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2021-03-14 12:53 UTC
Labels: Waiting on OP, bug
