### ISSUE TITLE
installation should not require acceptance of license agreement

### ISSUE THREAD

**Issue by ChetHosey** [AdoptOpenJDK/openjdk-support#106] opened 2020-05-20 20:46 UTC
The installer isn't used when modifying or redistributing the software; it's only needed for people who intend to use the software.

The GPL states that users are allowed to *use* licensed software without accepting the license agreement, but that modification and redistribution are only allowed when the terms are accepted.

Despite the language of the GPL ("You are not required to accept this License, since you have not signed it."), and the install process being unrelated to modification or redistribution, the installer won't proceed without the user's acceptance of the license terms.

This requirement contradicts the licensing terms and should not be forced upon users at install time.

* **Platform and architecture (e.g. Linux/x64**: Windows

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: jdk-11.0.7+10.2 installer

* **Variant e.g. HotSpot or OpenJ9**: HotSpot

* **Have you tested it with other vendors' java**: n/a

* **Steps to reproduce**:
1) Run installer
2) Click through to license screen
3) Observe that text of GPL shown on license screen states: "You are not required to accept this License, since you have not signed it."

* **Error messsage and/or description of what is not working as expected**:

"Next" button is disabled until user checks "I accept the terms in the License Agreement"

**Comment by aahlenst** [comment] 2020-05-21 06:34
Duplicate of https://github.com/AdoptOpenJDK/openjdk-installer/issues/162.

**Closed by aahlenst** 2020-05-21 06:34 UTC
