### ISSUE TITLE
Does not draws graphs in javamelody [sparc build]

### ISSUE THREAD

**Issue by birkoffe** [AdoptOpenJDK/openjdk-support#11] opened 2019-01-15 13:40 UTC
Does not draws graphs in javamelody
In log file there is no errors and warns

$ uname -a
SunOS test 5.11 11.3 sun4v sparc sun4v

$ /site/share/java/jdk8u192-b12/bin/java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-201901120427-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)

![adoptopenjdk](https://user-images.githubusercontent.com/828228/51183916-55693580-1905-11e9-8ec1-e3285a5ec94f.PNG)

$ /site/share/java/jdk1.8.0_191/bin/java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

![oraclejdk](https://user-images.githubusercontent.com/828228/51183944-687c0580-1905-11e9-8362-99c0f5744069.PNG)

**Comment by aahlenst** [comment] 2020-05-30 12:01
This looks like a duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/693. https://github.com/AdoptOpenJDK/openjdk-build/issues/693#issuecomment-439983961 might help. If not, please report back.

**Closed by aahlenst** 2020-05-30 12:01 UTC
