### ISSUE TITLE
Send Mails via Office 365 SMTP not working with Version 11

### ISSUE THREAD

**Issue by Orgadata** [AdoptOpenJDK/openjdk-support#17] opened 2019-11-19 13:06 UTC
We use jdk-11.0.5+10 with a software application and try to send mails via Office 365 SMTP. While we are facing no problems with any version OpenJDK Version 8, it's not working with version 11 anymore.

`Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not convert socket to TLS;`

We us [smtp.office365.com](url) as our SMTP server.

**Comment by andvasp** [comment] 2020-01-15 01:25
I am facing the same problem. My company overwrites the certificates with another of its own. I export this certificate using Chrome and import it to Java via keytool to the lib/security/cacerts file. In Java 8 works fine, but in Java 11 this error happens. In another network works fine both version.

**Comment by aahlenst** [comment] 2020-05-09 12:43
I am not able to reproduce this. Please share a code sample that I can run (public GitHub repository is best). I'll bring my own Office 365 account.

If we don't hear back in a week or so, I'm going to close this issue.

**Comment by aahlenst** [comment] 2020-05-19 08:58
Closing due to lack of requested feedback.

**Closed by aahlenst** 2020-05-19 08:58 UTC
Labels: Waiting on OP
