### ISSUE TITLE
java.base/java.io.ExpiringCache.cleanup java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jackjeyis** [AdoptOpenJDK/openjdk-support#230] opened 2020-12-18 09:08 UTC
## Summary
java.lang.ArrayIndexOutOfBoundsException: Index 255 out of bounds for length 255
	at java.base/java.io.ExpiringCache.cleanup(ExpiringCache.java:120)
	at java.base/java.io.ExpiringCache.get(ExpiringCache.java:76)
	at java.base/java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:158)
	at java.base/java.io.File.getCanonicalPath(File.java:618)
	at org.apache.catalina.webresources.AbstractFileResourceSet.file(AbstractFileResourceSet.java:90)
	at org.apache.catalina.webresources.DirResourceSet.getResource(DirResourceSet.java:101)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2228)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:829)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1278)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1137)

run environment

Using CATALINA_BASE:   /opt/tomcat
Using CATALINA_HOME:   /opt/tomcat
Using CATALINA_TMPDIR: /opt/tomcat/temp
Using JRE_HOME:        /usr/java/jdk11
Using CLASSPATH:       /opt/tomcat/bin/bootstrap.jar:/opt/tomcat/bin/tomcat-juli.jar:/opt/tomcat/bin/ctrip-tomcat-patch-1.0.0.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Server version: Apache Tomcat/8.5.32
Server built:   Jun 20 2018 19:50:35 UTC
Server number:  8.5.32.0
OS Name:        Linux
OS Version:     4.19.118-1.el7.centos.x86_64
Architecture:   amd64
JVM Version:    11.0.4+11
JVM Vendor:     AdoptOpenJDK

**Comment by aahlenst** [comment] 2020-12-18 10:35
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Furthermore, please explain what makes you think that the JDK is the problem here.

**Comment by aahlenst** [comment] 2020-12-25 13:47
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-12-25 13:47 UTC
Labels: Waiting on OP, bug

**Comment by hedrickbt** [comment] 2022-02-02 20:07
We are seeing this issue with 

Tomcat 9.0.43
AdoptOpenJDK jdk-11.0.10+9
Windows Server 2019

We only seeing this in 1 application so far, out of many.  We have not been able to create a reproducible case.

2/1/2211:25:27.000 PM | Feb 01, 2022 11:25:27 PM org.apache.catalina.core.StandardWrapperValve invoke SEVERE: Servlet.service() for servlet [servlet] in context with path [/CropQuoting] threw exception java.lang.ArrayIndexOutOfBoundsException: Index 199 out of bounds for length 199 	at java.base/java.io.ExpiringCache.cleanup(ExpiringCache.java:120) 	at java.base/java.io.ExpiringCache.get(ExpiringCache.java:76) 	at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:416) 	at java.base/java.io.File.getCanonicalPath(File.java:620) 	at org.apache.catalina.webresources.AbstractFileResourceSet.file(AbstractFileResourceSet.java:94) 	at org.apache.catalina.webresources.DirResourceSet.getResource(DirResourceSet.java:101) 	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281) 	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62) 	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216) 	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225) 	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2316) 	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:864) 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333) 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187) 	at com.rainhail.cropquoting.config.ErrorLoggingFilter.doFilter(ErrorLoggingFilter.java:29) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)

**Comment by karianna** [comment] 2022-02-03 11:28
@hedrickbt - Can you please try with the latest 11.0.14

**Comment by hedrickbt** [comment] 2022-02-07 12:57
@karianna ,

We are currently in a freeze for JVM changes.  For now, I am looking at adding the following system properties for the app/JVM exhibiting the issue.

sun.io.useCanonCaches=false
sun.io.useCanonPrefixCache=false
