### ISSUE TITLE
fatal error: PreserveExceptionMark destructor expects no pending exceptions

### ISSUE THREAD

**Issue by chrjohn** [AdoptOpenJDK/openjdk-support#227] opened 2020-12-16 00:06 UTC
## Summary

JVM crashes with attached crash log.
[hs_err_pid90389.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5699411/hs_err_pid90389.log)

I am well aware that this issue will be closed without a reproducer. I just wanted to have a reference to this problem and also maybe others have the same problem and we could find similarities in the software used.

We faced this problem only once to date. Used software: Payara 5.2020.4 with Solr 5 on Debian 10 on Proxmox.

First lines:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (preserveException.cpp:46), pid=90389, tid=131697
#  fatal error: PreserveExceptionMark destructor expects no pending exceptions
```

First threads:

```
---------------  T H R E A D  ---------------

Current thread (0x00007f593c023800):  JavaThread "http-thread-pool::http-listener-1(30)" daemon [_thread_in_vm, id=131697, stack(0x00007f58c7dd9000,0x00007f58c7eda000)]

Stack: [0x00007f58c7dd9000,0x00007f58c7eda000],  sp=0x00007f58c7ed6fb0,  free space=1015k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xe3a6de]  VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long)+0x37e
V  [libjvm.so+0xe3b36f]  VMError::report_and_die(Thread*, void*, char const*, int, char const*, char const*, __va_list_tag*)+0x2f
V  [libjvm.so+0x68e38a]  report_fatal(char const*, int, char const*, ...)+0x10a
V  [libjvm.so+0xc797da]  PreserveExceptionMark::~PreserveExceptionMark()+0x4a
V  [libjvm.so+0x891bfa]  java_lang_Throwable::detail_message(oopDesc*)+0x4a
V  [libjvm.so+0x7467c6]  Exceptions::log_exception(Handle, char const*)+0x56
V  [libjvm.so+0x886ed1]  InterpreterRuntime::exception_handler_for_exception(JavaThread*, oopDesc*)+0x4c1
j  org.apache.solr.parser.SolrQueryParserBase.parse(Ljava/lang/String;)Lorg/apache/lucene/search/Query;+79
J 39253 c1 org.apache.solr.search.ExtendedDismaxQParser.parseOriginalQuery(Lorg/apache/solr/search/ExtendedDismaxQParser$ExtendedSolrQueryParser;Ljava/lang/String;Ljava/util/List;Lorg/apache/solr/search/ExtendedDismaxQParser$ExtendedDismaxConfiguration;)Lorg/apache/lucene/search/Query; (113 bytes) @ 0x00007f5a1f213454 [0x00007f5a1f2132c0+0x0000000000000194]
J 37667 c1 org.apache.solr.search.ExtendedDismaxQParser.parse()Lorg/apache/lucene/search/Query; (443 bytes) @ 0x00007f5a20072b64 [0x00007f5a20071b80+0x0000000000000fe4]
...
```

## Steps to reproduce

Unfortunately not able to reproduce.

## Expected results

Just don't crash.

## Actual results

Crash.

## Triaging info

Java version:

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

What is your operating system and platform?
Debian GNU/Linux 10 (buster) on x86-64

Linux 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 GNU/Linux

Proxmox

**Comment by karianna** [comment] 2020-12-16 16:25
Can you try 11.0.9.1 - it contained a couple of C2 crashing fixes.

**Comment by chrjohn** [comment] 2020-12-17 00:48
@karianna , thanks for your reply.
Up to now the error did not resurface. But will make sure to use a more recent OpenJDK build...

**Comment by aahlenst** [comment] 2020-12-25 11:34
Following a short discussion on Slack, I'll close this issue because there's nothing we can do until the problem can be reliably reproduced. Happy to reopen as soon as additional information is provided.

**Closed by aahlenst** 2020-12-25 11:34 UTC
Labels: Waiting on OP, bug, not reproducible

**Comment by chrjohn** [comment] 2021-06-14 22:06
Just for the record: we did not experience another crash for several months since updating to 11.0.10. Could be pure luck but maybe there really was some strange bug triggering this.
