### ISSUE TITLE
Crash when loading native libs in a tomcat environment

### ISSUE THREAD

**Issue by manfredstephanmueller** [AdoptOpenJDK/openjdk-support#210] opened 2020-11-20 09:42 UTC
## Expected results
Tomcat does not crash and starts.

## Actual results
Tomcat is crashing and does not start therefore.

## Triaging info

Java version:
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)

What is your operating system and platform?
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

How did you install Java?
binary archive

Did it work before?
Not on this system and not on other systems using adopt jdk.

Did you test with other Java versions?
Yes, it does not crash with a build in openjdk.

I attached a core dump!
[hs_err_pid20840.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5572646/hs_err_pid20840.log)

**Comment by aahlenst** [comment] 2020-11-20 10:54
What makes you think the problem is the JDK?

**Comment by manfredstephanmueller** [comment] 2020-11-20 11:51
I don’t know if the problem is the jdk. But with older versions of java I never had any problems loading this native libs in this service. Also the default jdk did not crash. So I think the adoptjdk may be the reason for the crash.

**Comment by aahlenst** [comment] 2020-11-20 11:59
The crash happens in libicconvert.so. It's not part of the JDK. Looks like something between the JDK and libicconvert or within libicconvert makes unsafe assumptions and passes invalid pointers.

> Yes, it does not crash with a build in openjdk.

Does this mean it works with Red Hat's build of 8u272? If you don't have one, you can get it from https://adoptopenjdk.net/upstream.html.

**Comment by manfredstephanmueller** [comment] 2020-11-23 10:04
Hi,
The crash didn’t happen with the openjdk which is part of the os, installed with sudo yum install …

OpenJDK: openjdk-8u262-b10-linux

This worked on centos 7 and on Debian GNU/Linux 9 too.

Best regards
Manfred

**Comment by aahlenst** [comment] 2020-11-23 10:09
Please provide steps to reproduce if you want us to work on it.

**Comment by aahlenst** [comment] 2020-11-23 10:34
> The crash didn’t happen with the openjdk which is part of the os, installed with sudo yum install …
> OpenJDK: openjdk-8u262-b10-linux

You really have to compare the same versions. You're using AdoptOpenJDK 272, but 262 on CentOS. That's not the same.

**Comment by manfredstephanmueller** [comment] 2020-11-24 07:59
This is what I did to get the latest openjdk for centos, which did not crash:

yum install java-1.8.0-openjdk

# yum info java-1.8.0-openjdk
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
* base: centosmirror.netcup.net
* extras: de.mirrors.clouvider.net
* updates: ftp.plusline.net<ftp://ftp.plusline.net>
Installed Packages
Name        : java-1.8.0-openjdk
Arch        : x86_64
Epoch       : 1
Version     : 1.8.0.262.b10
Release     : 0.el7_8
Size        : 646 k
Repo        : installed
From repo   : updates
Summary     : OpenJDK Runtime Environment 8
URL         : http://openjdk.java.net/
License     : ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib
Description : The OpenJDK runtime environment.

Available Packages
Name        : java-1.8.0-openjdk
Arch        : i686
Epoch       : 1
Version     : 1.8.0.272.b10
Release     : 1.el7_9
Size        : 304 k
Repo        : updates/7/x86_64
Summary     : OpenJDK Runtime Environment 8
URL         : http://openjdk.java.net/
License     : ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib
Description : The OpenJDK runtime environment.

Name        : java-1.8.0-openjdk
Arch        : x86_64
Epoch       : 1
Version     : 1.8.0.272.b10
Release     : 1.el7_9
Size        : 304 k
Repo        : updates/7/x86_64
Summary     : OpenJDK Runtime Environment 8
URL         : http://openjdk.java.net/
License     : ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib
Description : The OpenJDK runtime environment.


Best regards
Manfred Müller

**Comment by aahlenst** [comment] 2020-11-24 08:26
Please provide steps (and code) to reproduce if you want us to work on it.

**Comment by manfredstephanmueller** [comment] 2020-11-24 08:41
I tried to upload my war, but it seems to be too large (112 MB). Is there another way to upload the war file?

Best regards
Manfred

**Comment by aahlenst** [comment] 2020-11-24 09:54
I don't accept precompiled code. If the problem is too big for a single class with a `main()` method, a sample project on GitHub is a good idea. Example: https://github.com/aahlenst/cacert-test/

**Comment by jerboaa** [comment] 2020-11-24 10:06
> # yum info java-1.8.0-openjdk
> Installed Packages Name : java-1.8.0-openjdk
> Arch : x86_64
> Epoch : 1 Version : 1.8.0.262.b10
> Release : 0.el7_8 Size

The other package version `1.8.0.272.b10` is **available** in the repo. `yum info` is not a good tool for this reason. Please use `rpm -q java-1.8.0-openjdk` in order to query the *installed* version of the system OpenJDK package. So, to me, it still looks like you are comparing 8u262 (system OpenJDK) with 8u272 (AdoptOpenJDK). Please check.

**Comment by aahlenst** [comment] 2020-12-25 11:35
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-12-25 11:35 UTC
Labels: Waiting on OP, bug
