### ISSUE TITLE
Wrong default heap size (11.0.4_11 Windows)

### ISSUE THREAD

**Issue by cypher256** [AdoptOpenJDK/openjdk-support#35] opened 2019-10-01 14:45 UTC
**Platform:**
Windows 10 64bit

**Architecture:**
x64_windows_hotspot

Heap size -Xmx not specified. (Eclipse eclipse.ini)
Physical Memory: 4GB

OpenJDK11U-jdk_x64_windows_hotspot_11.0.3_7
-> Heap Size 1GB (Probably 1/4 of physical memory)
OpenJDK11U-jdk_x64_windows_hotspot_11.0.4_11
-> Heap Size 256MB (default?)

**Comment by Phillipus** [comment] 2020-05-13 17:55
Hi there, is there a fix for this issue?

**Comment by Phillipus** [comment] 2020-05-13 18:14
I see this in 11.0.5 and 11.0.7 HotSpot, but not OpenJ9 11.0.7.

**Comment by Phillipus** [comment] 2020-05-13 18:54
> On 11.0.4 and later, it seems that the client VM is used.
> When I specified the following in eclipse.ini, it became 1/4 of physical memory.
> 
> ```
> -vm
> {java home dir}/bin/server
> ```

I can confirm that is the case.

**Comment by Phillipus** [comment] 2020-05-13 21:33
> On 11.0.4 and later, it seems that the client VM is used.
> When I specified the following in eclipse.ini, it became 1/4 of physical memory.
> 
> ```
> -vm
> {java home dir}/bin/server
> ```

On Windows, 11.0.3 doesn't have a `bin/client` folder whereas on 11.0.5 it does. Deleting the  `bin/client` folder on 11.0.5 actually fixes this problem.

**Comment by aahlenst** [comment] 2020-05-14 11:14
The "problem" seems to be that AdoptOpenJDK includes a client VM. The upstream builds do not:

```
> bin/java -client -XX:+PrintFlagsFinal -version | Select-String -Pattern "(heapsize|permsize|version)"

   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 268435456                                 {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 4294967296                                {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5830732                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122913754                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122913754                              {pd product} {ergonomic}
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)
```

As you can see, I passed the `-client` flag, but I got a OpenJDK 64-Bit **Server** VM.

Now, AdoptOpenJDK:

```
> bin/java -client -XX:+PrintFlagsFinal -version | Select-String -Pattern "(heapsize|permsize|version)"

   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 16777216                                  {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 268435456                                 {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5242880                                {pd product} {default}
    uintx NonProfiledCodeHeapSize                  = 0                                      {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 0                                      {pd product} {ergonomic}
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Client VM AdoptOpenJDK (build 11.0.7+10, mixed mode)


> bin/java -server -XX:+PrintFlagsFinal -version | Select-String -Pattern "(heapsize|permsize|version)"

   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 268435456                                 {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 4294967296                                {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5830732                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122913754                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122913754                              {pd product} {ergonomic}
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)


> bin/java -XX:+PrintFlagsFinal -version | Select-String -Pattern "(heapsize|permsize|version)"

   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 268435456                                 {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 4294967296                                {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5830732                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122913754                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122913754                              {pd product} {ergonomic}
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

We actually provide both with the server VM being the default. With the client VM the limits are significantly lower. This is consistent with https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html#default_heap_size and https://docs.oracle.com/javase/7/docs/technotes/guides/vm/server-class.html (my test machine has 8 cores and 16 GB memory).

In the past, it was generally recommended that GUI applications use the client VM (faster startup).  Maybe that's the reason Eclipse tries to use the client VM? [According to Eclipse wiki](https://wiki.eclipse.org/Eclipse.ini), eclipse.ini is the place to override the VM selection.

Considering all things, I don't think it's either a bug in Eclipse nor in AdoptOpenJDK.

**Comment by Phillipus** [comment] 2020-05-14 11:25
> We actually provide both with the server VM being the default.

But the default now in AdoptOpenJDK is the client VM?

> Considering all things, I don't think it's either a bug in Eclipse nor in AdoptOpenJDK.

Sure. The problem is that when using, say, 11.0.3 you got the Server VM and in 11.0.4 and later you get a big surprise.

**Comment by Phillipus** [comment] 2020-05-14 12:27
The issues I see are:

- AdoptOpenJDK jdk-11.0.4+11 introduced a Client VM in addition to the Server VM in the `bin` folder
- Because of this, the default VM on Windows 64-bit changed from Server VM to Client VM
- This was not documented in the Release Notes (I'm happy to be corrected on this one)
- The Client VM (at least on Windows) does not allocate the same max heap size as the Server VM

**Comment by karianna** [comment] 2020-05-14 12:39
> The issues I see are:
> 
> * AdoptOpenJDK jdk-11.0.4+11 Windows version introduced a Client VM in addition to the Server VM in the `bin` folder
> * Because of this, the default VM on Windows 64-bit changed from Server VM to Client VM
> * This was not documented in the Release Notes (I'm happy to be corrected on this one)
> * The Client VM (at least on Windows) does not allocate the same max heap size as the Server VM

This is super interesting.  Even if we ship both VMS I believe the JVM should select server mode depending on the host characteristics it's running on.

You can pass the `-server` flag as a short term workaround

**Comment by Phillipus** [comment] 2020-05-14 12:44
> Even if we ship both VMs I believe the JVM should select server mode depending on the host characteristics it's running on.

See https://docs.oracle.com/javase/7/docs/technotes/guides/vm/server-class.html That would make the Client VM the default on Windows.

**Comment by Phillipus** [comment] 2020-05-14 12:46
> Even if we ship both VMs I believe the JVM should select server mode depending on the host characteristics it's running on.

"depending on the host characteristics" seems a bit random. Some machines would display this issue, and others not.

**Comment by karianna** [comment] 2020-05-14 12:48
> > Even if we ship both VMs I believe the JVM should select server mode depending on the host characteristics it's running on.
> 
> See https://docs.oracle.com/javase/7/docs/technotes/guides/vm/server-class.html That would make the Client VM the default on Windows.

Hmm, this is challenging.  I think a bunch of Windows users will use Java for desktop gaming (like Minecraft) and others for running server workloads.  So I'm not sure if dropping client VM would 'solve' this.

I'd be curious to understand what Azul and Oracle do in this case, anyone know?

**Comment by aahlenst** [comment] 2020-05-14 12:58
@Phillipus As you can see from the examples I gave above, the server VM is the default with AdoptOpenJDK 64 bit. Look closely at the output of `java -version`. It prints the VM type. The last example has neither the `-client` nor the `-server` switch.

With 32 bit OpenJDK, the client VM is the default, even on a 64 bit system. The server VM should never be the default on a 64 bit system with a 64 bit JDK. If you find a 64 bit system with a 64 bit JDK that defaults to the client VM, please share the details (CPU, RAM, OS).

@karianna OpenJDK built by Red Hat does not include the client VM. Zulu does not include the client VM, too.

**Comment by Phillipus** [comment] 2020-05-14 13:00
@aahlenst Not on Windows it isn't. You're using the Linux version.

**Comment by Phillipus** [comment] 2020-05-14 13:01
>  If you find a 64 bit system with a 64 bit JDK that defaults to the client VM, please share the details (CPU, RAM, OS).

Windows 10 64-bit.
AdoptOpenJDK Hotspot 11.0.4 and later versions,

**Comment by aahlenst** [comment] 2020-05-14 13:11
<img width="1091" alt="vm_type" src="https://user-images.githubusercontent.com/198908/81938325-0dd7e400-95f5-11ea-847e-bcae248432c5.png">

What am I missing?

**Comment by Phillipus** [comment] 2020-05-14 13:17
> What am I missing?

I don't know

![Image 1](https://user-images.githubusercontent.com/600504/81938876-7327d700-95ed-11ea-8a7e-403c64c01fa6.png)

Windows 10 Pro 64-bit build 18362.778

**Comment by aahlenst** [comment] 2020-05-14 13:19
Do you have a release file in that JDK (topmost folder)? Can you paste the contents, just to be sure?

**Comment by Phillipus** [comment] 2020-05-14 13:20
> Do you have a release file in that JDK (topmost folder)? Can you paste the contents, just to be sure?

```
IMPLEMENTOR="AdoptOpenJDK"
IMPLEMENTOR_VERSION="AdoptOpenJDK"
JAVA_VERSION="11.0.7"
JAVA_VERSION_DATE="2020-04-14"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.crypto.mscapi jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.internal.le jdk.internal.opt jdk.jartool jdk.javadoc jdk.jcmd jdk.management jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.pack jdk.rmic jdk.scripting.nashorn jdk.scripting.nashorn.shell jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"
OS_ARCH="x86"
OS_NAME="Windows"
SOURCE=".:git:081c5fa55182"

```

**Comment by aahlenst** [comment] 2020-05-14 13:21
There it is: `OS_ARCH="x86"`. You have a 32 bit SDK. That defaults to the client VM, even on a 64 bit machine.

**Comment by Phillipus** [comment] 2020-05-14 13:27
> There it is: OS_ARCH="x86". You have a 32 bit SDK. That defaults to the client VM, even on a 64 bit machine.

Apologies. I've been downloading so many different versions I chose the wrong one. Yes, it defaults to Server. Now I have to go back to the original issue in the OP and figure this out again.

**Comment by Phillipus** [comment] 2020-05-14 13:49
Right then. Apologies for the confusion, I had delved into this but somehow mixed up my 32-bit and 64-bit versions of 11.0.7 which has thrown things awry. I'll start again...

This seems to be about how Eclipse sees the installed VM.

If I install 11.0.3 on Windows 64-bit and run Eclipse. Eclipse's Configuration details are as follows:

```
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.3+7
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=AdoptOpenJDK
java.vendor.url=https://adoptopenjdk.net/
java.vendor.url.bug=https://github.com/AdoptOpenJDK/openjdk-build/issues
java.vendor.version=AdoptOpenJDK
java.version=11.0.3
java.version.date=2019-04-16
java.vm.compressedOopsMode=32-bit
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=AdoptOpenJDK
java.vm.version=11.0.3+7
```

Note:

```
java.vm.name=OpenJDK 64-Bit Server VM
```

If I install 11.0.7 on Windows 64-bit and run Eclipse. Eclipse's Configuration details are as follows:

```
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.7+10
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=AdoptOpenJDK
java.vendor.url=https://adoptopenjdk.net/
java.vendor.url.bug=https://github.com/AdoptOpenJDK/openjdk-support/issues
java.vendor.version=AdoptOpenJDK
java.version=11.0.7
java.version.date=2020-04-14
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Client VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=AdoptOpenJDK
java.vm.version=11.0.7+10
```

Note:

```
java.vm.name=OpenJDK 64-Bit Client VM
```

So is this a case of Eclipse looking for the wrong thing? Or something else?

**Comment by aahlenst** [comment] 2020-05-14 14:12
As I wrote in https://github.com/AdoptOpenJDK/openjdk-support/issues/35#issuecomment-628565292:
> In the past, it was generally recommended that GUI applications use the client VM (faster startup). Maybe that's the reason Eclipse tries to use the client VM? [According to Eclipse wiki](https://wiki.eclipse.org/Eclipse.ini), eclipse.ini is the place to override the VM selection.

I don't know if it's a bug in Eclipse or a deliberate choice. I had to dig into the Eclipse launcher to find out and that's not something I fancy doing. For the moment, I don't consider it a bug in AdoptOpenJDK.

**Comment by Phillipus** [comment] 2020-05-14 14:41
> For the moment, I don't consider it a bug in AdoptOpenJDK.

I agree.

My thinking is that if, on Windows 64-bit, the default VM is Server (as we can see from `java -version`) then Eclipse should respect that.

I commented on https://bugs.eclipse.org/bugs/show_bug.cgi?id=553538 but I get the feeling that the Eclipse people disagree.

**Comment by Phillipus** [comment] 2020-05-14 14:43
But getting back to the OP...

Is it expected behaviour that the Client VM allocates only 256MB for the maximum heap if otherwise not specified? Unlike the Server VM which will allocate 1/4 of system memory.

**Comment by aahlenst** [comment] 2020-05-14 16:05
Quoting https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html#default_heap_size:

> For example, if your computer has 128 MB of physical memory, then the maximum heap size is 64 MB, and greater than or equal to 1 GB of physical memory **results in a maximum heap size of 256 MB**.

(emphasis mine)

**Comment by Phillipus** [comment] 2020-05-14 16:11
> Quoting https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html#default_heap_size:
> 
> > For example, if your computer has 128 MB of physical memory, then the maximum heap size is 64 MB, and greater than or equal to 1 GB of physical memory **results in a maximum heap size of 256 MB**.
> 
> (emphasis mine)

OK, thanks.

In that case my research into this is concluded.

It is an Eclipse issue, and they are today even attempting a fix - https://bugs.eclipse.org/bugs/show_bug.cgi?id=553538#c10

(Sorry about muddying the waters with me mistakenly testing with a 32-bit version. I think I downloaded several different versions on my machine and got them mixed up.)

**Comment by aahlenst** [comment] 2020-05-14 16:14
@Phillipus No worries. I downloaded the wrong version myself more often than not. We should fix this…

I close this issue. Please report back if there's something left for us to do.

**Closed by aahlenst** 2020-05-14 16:14 UTC
Labels: bug
