### ISSUE TITLE
Bug JDK 8.222 and 8.232 + tomcat + zabbix many close_wait connections

### ISSUE THREAD

**Issue by gehengfeng** [AdoptOpenJDK/openjdk-support#116] opened 2020-06-03 04:08 UTC
* **Platform and architecture (e.g. Linux/x64**:
windows 2012
* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
1.8.222 and 1.8.232
* **Variant e.g. HotSpot or OpenJ9**:
HotSpot 
* **Have you tested it with other vendors' java**:
yes
* **Steps to reproduce**:
our application is run by OpenJDK 1.8.232. 
it's run on port 443.
we use Zabbix to monitor this port by net.tcp.service.
there are many connections from zabbix to our application 443 port with close_wait status.
then the service not working when the close_wait connections too many.

then we switch the JRE from OpenJDK 1.8.232 to Oracle JRE 1.8.211, there are no close_wait connection from the zabbix server to our application 443 port.

so we think it's OpenJDK issue. I can provide the Java heap dump file when the issue occur.

it's similar to this issue:
https://bugs.openjdk.java.net/browse/JDK-8221395

* **Error messsage and/or description of what is not working as expected**:
the monitor connect the server every 1 minutes. so the connections is high. and the connections should close fine when the close from zabbix. but it's stay at close_wait affect the application workinng.

**Comment by aahlenst** [comment] 2020-06-03 06:36
Thank you for getting in touch.

The linked JBS issue concerns the new HttpClient which is only available since OpenJDK 11.

If you want to compare OpenJDK to Oracle JDK, you have to test with the same versions and use the most recent ones. For OpenJDK this would be 8u252 and for Oracle JDK 8u251.

If you want further help, supply a test case that reproduces the issue. The linked JBS issue gives you an idea what is needed.

**Comment by gehengfeng** [comment] 2020-06-03 09:50
thanks. I have upgrade my two test environment to OpenJDK 8u252 and Oracle JDK 8u251. I will update you when I reproduces the issue.

**Comment by gehengfeng** [comment] 2020-06-12 12:44
I upgrade the server 01 to OpenJDK 8u252 and server02 to Oracle JRE 8u251, 
in the past days, we use zabbix monitor the close_wait connection number.
there are no more than 3 close_wait connection on OpenJDK 8u252, but there are many times in the pass days.
there are 1 close_wait connection on Oracle JRE 8u251 one time in the pass days.
today I find there are 90 close_wait connection on the server 01 with OpenJDK 8u252.
there are no close_wait connections on server02 with Oracle 8u251.

I have dump the java heap.

what can I do next?

thanks.

Hengfeng

**Comment by aahlenst** [comment] 2020-06-12 12:56
To move forward, we need to do two things:

* Find out if the issue is AdoptOpenJDK-specific or not. Testing with https://adoptopenjdk.net/upstream.html would help in that regard.
* A sample project that reproduces the issue and that you can share. Even if we report the issue to OpenJDK, they most likely won't work on it without a reproducible test case. https://bugs.openjdk.java.net/browse/JDK-8221395 shows how a reproducible test case could look like.

**Comment by aahlenst** [comment] 2020-07-10 14:45
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-07-10 14:45 UTC
Labels: Waiting on OP
