### ISSUE TITLE
Error 1067 while starting Tomcat service on Windows server.

### ISSUE THREAD

**Issue by shilpi201** [AdoptOpenJDK/openjdk-support#158] opened 2020-08-04 11:14 UTC
Hello Team,
we have recently build new windows BSI server but at a sudden restart of system by windows team  the  JVM was crashed and we are getting issue while starting Tomcat.  although repairing JVM fixed this issue.

could you please let us know any specfic reason for the same?
Regrads:
Shilpi Rana

**Comment by aahlenst** [comment] 2020-08-04 11:17
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by shilpi201** [comment] 2020-08-04 12:04
Hello  team,

We  installed new BSI server, which include  JAVA and tomcat. Earlier when we installed   tomcat services were running fine. After system reboot we are getting issue "apache tomcat 7 service error 1067: the process terminated unexpectedly"

Even after repairing JVM it got fixed, but we need to know is this JAVA bug ? or ever time  when windows got rebooted we wil get this issue.  Logs has been attached
[hs_err_pid932.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5021940/hs_err_pid932.log)
.


Please let me know what other information you are looking for?

**Comment by aahlenst** [comment] 2020-08-04 12:21
What is a "BSI server"?

> apache tomcat 7 service error 1067

The crash dump you attached indicates Tomcat 9 is being used.

> Even after repairing JVM it got fixed

Can you elaborate on what "repairing JVM" means? What exactly did you do?

> we need to know is this JAVA bug

I'd say it's unlikely. Looking at the crash dump and the exception type, I guess the problem is in Tomcat. It passes the wrong data to the JVM which causes it to crash.

**Comment by aahlenst** [comment] 2020-08-15 10:16
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Closed by aahlenst** 2020-08-15 10:16 UTC
Labels: Waiting on OP
